// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunBlockRetentionLedgerPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/block-retention-ledger/page', params })

export const getBoxunBlockRetentionLedger = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/block-retention-ledger/get?id=' + id })

export const getBoxunBlockRetentionLedgerSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/block-retention-ledger/simple-list', params })

export const listBoxunBlockRetentionLedgerByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/block-retention-ledger/list-by-condition', data })

export const createBoxunBlockRetentionLedger = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/block-retention-ledger/create', data })

export const upsertBoxunBlockRetentionLedger = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/block-retention-ledger/upsert', data })

export const updateBoxunBlockRetentionLedger = (data: EntityInput) => request.put<number>({ url: '/boxun/block-retention-ledger/update', data })

export const deleteBoxunBlockRetentionLedger = (id: EntityId) => request.delete<boolean>({ url: '/boxun/block-retention-ledger/delete?id=' + id })

export const deleteBoxunBlockRetentionLedgerList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/block-retention-ledger/delete-list', params: { ids: ids.join(',') } })

export interface SpecimenStrengthEvaluationRequest {
  strengthGrade: string
  representativeValues: number[]
}

export interface SpecimenStrengthEvaluationResult {
  strengthGrade: string
  standardValue: number
  sampleSize: number
  method: 'NON_STATISTICAL' | 'STATISTICAL_UNKNOWN_SIGMA'
  methodLabel: string
  representativeValues: number[]
  mean: number
  minimum: number
  standardDeviation?: number | null
  lambda1?: number | null
  lambda2?: number | null
  lambda3?: number | null
  lambda4?: number | null
  meanRequirement: number
  minimumRequirement: number
  meanQualified: boolean
  minimumQualified: boolean
  qualified: boolean
  conclusion: string
}

export const evaluateBoxunBlockRetentionLedgerStrength = (data: SpecimenStrengthEvaluationRequest) =>
  request.post<SpecimenStrengthEvaluationResult>({ url: '/boxun/block-retention-ledger/evaluate-strength', data })

/** 去委托：按楼号+成型日期生成委托单与样品。 */
export const entrustBoxunBlockRetentionLedger = (ids: EntityId[], type?: number) =>
  request.post<number>({
    url: '/boxun/block-retention-ledger/entrust-the-test-block',
    data: ids.map((id) => String(id)),
    params: type === undefined ? undefined : { type }
  })

/** 生成套件（type 1 标养、2 抗渗、3 同养、4 拆模）。 */
export const generateBoxunBlockRetentionLedgerKit = (id: EntityId, type: number) =>
  request.post<string[]>({ url: '/boxun/block-retention-ledger/generate-multi-kit', params: { id, type } })

/** 下载套件。 */
export const downloadBoxunBlockRetentionLedgerKit = (id: EntityId, type: number) =>
  request.download({ url: '/boxun/block-retention-ledger/download-various-packages', params: { id, type } })

/** 生成同条件养护委托单。 */
export const downloadBoxunBlockRetentionLedgerTtjOrder = (id: EntityId) =>
  request.download({ url: '/boxun/block-retention-ledger/gen-ttj-wtd', params: { id } })

/** 生成拆模委托单。 */
export const downloadBoxunBlockRetentionLedgerCmOrder = (id: EntityId) =>
  request.download({ url: '/boxun/block-retention-ledger/gen-cm-wtd', params: { id } })
