<!-- generated by studio，请勿手工修改。 -->
<template>
  <ContentWrap>
    <el-form ref="queryFormRef" :inline="true" :model="queryParams" class="-mb-15px">
        <el-form-item label="楼号" prop="buildingNo">
          <el-input v-model="queryParams.buildingNo" clearable placeholder="请输入楼号" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="工程部位" prop="concatPosition">
          <el-input v-model="queryParams.concatPosition" clearable placeholder="请输入工程部位" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="强度等级" prop="strengthGrade">
          <el-input v-model="queryParams.strengthGrade" clearable placeholder="请输入强度等级" @keyup.enter="handleQuery" />
        </el-form-item>
      <el-form-item>
        <el-button @click="handleQuery"><Icon class="mr-5px" icon="ep:search" />查询</el-button>
        <el-button @click="resetQuery"><Icon class="mr-5px" icon="ep:refresh" />重置</el-button>
          <el-button type="primary" @click="openForm('create')">
            <Icon class="mr-5px" icon="ep:plus" />新增
          </el-button>
          <el-button type="warning" plain @click="openEvaluate()">
            <Icon class="mr-5px" icon="ep:data-analysis" />试块评定
          </el-button>
          <el-dropdown :disabled="checkedIds.length === 0" @command="handleEntrust(checkedIds, $event)">
            <el-button :disabled="checkedIds.length === 0" type="primary" plain>
              <Icon class="mr-5px" icon="ep:document-add" />去委托<Icon class="ml-5px" icon="ep:arrow-down" />
            </el-button>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item :command="0">全部套件</el-dropdown-item>
                <el-dropdown-item :command="1">标养</el-dropdown-item>
                <el-dropdown-item :command="2">抗渗</el-dropdown-item>
                <el-dropdown-item :command="3">同养</el-dropdown-item>
                <el-dropdown-item :command="4">拆模</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
          <el-button :loading="exportLoading" type="success" @click="handleExport">
            <Icon class="mr-5px" icon="ep:download" />导出
          </el-button>
          <el-button :disabled="checkedIds.length === 0" type="danger" @click="handleDeleteBatch">
            <Icon class="mr-5px" icon="ep:delete" />批量删除
          </el-button>
      </el-form-item>
    </el-form>
  </ContentWrap>

  <ContentWrap>
    <el-table v-loading="loading" :data="rows" @selection-change="handleSelectionChange">
        <el-table-column align="center" type="selection" width="55" />
      <el-table-column align="center" label="行号" width="90">
        <template #default="scope">{{ (queryParams.pageNo - 1) * queryParams.pageSize + scope.$index + 1 }}</template>
      </el-table-column>
        <el-table-column label="商混id" prop="fkShId" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" :formatter="dateFormatter" label="制作日期" prop="productionDate" width="180" />
        <el-table-column label="楼号" prop="buildingNo" min-width="120" show-overflow-tooltip />
        <el-table-column label="工程部位" prop="concatPosition" min-width="120" show-overflow-tooltip />
        <el-table-column label="强度等级" prop="strengthGrade" min-width="120" show-overflow-tooltip />
        <el-table-column label="抗渗等级" prop="impermeabilityLevel" min-width="120" show-overflow-tooltip />
        <el-table-column label="浇筑方量" prop="sumVolume" min-width="120" show-overflow-tooltip />
        <el-table-column label="标养试件组数" prop="numberOfStandardCuringSpecimenGroups" min-width="120" show-overflow-tooltip />
        <el-table-column label="抗渗试件组数" prop="numberOfSetsOfImpermeableTestPieces" min-width="120" show-overflow-tooltip />
        <el-table-column label="同养试件组数" prop="numberOfSpecimensInTheSameCulture" min-width="120" show-overflow-tooltip />
        <el-table-column label="拆模试件组数" prop="numberOfDemoldingSpecimenGroups" min-width="120" show-overflow-tooltip />
        <el-table-column label="同养温度" prop="syntrophicTemperature" min-width="120" show-overflow-tooltip />
        <el-table-column label="同养送检时的温度" prop="sjTemperature" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" fixed="right" label="操作" width="420">
          <template #default="scope">
            <el-button link type="primary" @click="openDetail(scope.row.id)">查看</el-button>
            <el-button link type="primary" @click="openForm('update', scope.row.id)">编辑</el-button>
            <el-button link type="warning" @click="openEvaluate(scope.row.strengthGrade)">评定</el-button>
            <el-dropdown @command="handleGenerateKit(scope.row.id, $event)">
              <el-button link type="primary">生成套件<Icon class="ml-2px" icon="ep:arrow-down" /></el-button>
              <template #dropdown>
                <el-dropdown-menu>
                  <el-dropdown-item :command="1">标养</el-dropdown-item>
                  <el-dropdown-item :command="2">抗渗</el-dropdown-item>
                  <el-dropdown-item :command="3">同养</el-dropdown-item>
                  <el-dropdown-item :command="4">拆模</el-dropdown-item>
                </el-dropdown-menu>
              </template>
            </el-dropdown>
            <el-dropdown @command="handleDownloadKit(scope.row.id, $event)">
              <el-button link type="primary">下载套件<Icon class="ml-2px" icon="ep:arrow-down" /></el-button>
              <template #dropdown>
                <el-dropdown-menu>
                  <el-dropdown-item :command="1">标养</el-dropdown-item>
                  <el-dropdown-item :command="2">抗渗</el-dropdown-item>
                  <el-dropdown-item :command="3">同养</el-dropdown-item>
                  <el-dropdown-item :command="4">拆模</el-dropdown-item>
                </el-dropdown-menu>
              </template>
            </el-dropdown>
            <el-button link type="primary" @click="handleTtjOrder(scope.row.id)">同养委托单</el-button>
            <el-button link type="primary" @click="handleCmOrder(scope.row.id)">拆模委托单</el-button>
            <el-button link type="danger" @click="handleDelete(scope.row.id)">删除</el-button>
          </template>
        </el-table-column>
    </el-table>
    <Pagination v-model:limit="queryParams.pageSize" v-model:page="queryParams.pageNo" :total="total" @pagination="getList" />
  </ContentWrap>

  <BoxunBlockRetentionLedgerForm ref="formRef" @success="getList" />
  <BoxunBlockRetentionLedgerDetail ref="detailRef" />
  <BoxunBlockRetentionLedgerEvaluate ref="evaluateRef" />
</template>

<script setup lang="ts">
import { dateFormatter } from '@/utils/formatTime'
import request from '@/config/axios'
import download from '@/utils/download'
import * as BoxunBlockRetentionLedgerApi from './BoxunBlockRetentionLedgerApi'
import BoxunBlockRetentionLedgerForm from './BoxunBlockRetentionLedgerForm.vue'
import BoxunBlockRetentionLedgerDetail from './BoxunBlockRetentionLedgerDetail.vue'
import BoxunBlockRetentionLedgerEvaluate from './BoxunBlockRetentionLedgerEvaluate.vue'

type BoxunBlockRetentionLedgerRow = Awaited<ReturnType<typeof BoxunBlockRetentionLedgerApi.getBoxunBlockRetentionLedgerPage>>['list'][number]
type EntityId = string | number

defineOptions({ name: 'BoxunBlockRetentionLedger' })

const message = useMessage()
const { t } = useI18n()
const loading = ref(false)
const total = ref(0)
const rows = ref<BoxunBlockRetentionLedgerRow[]>([])
const queryFormRef = ref()
const queryParams = reactive({
  pageNo: 1,
  pageSize: 10,
  buildingNo: '',
  concatPosition: '',
  strengthGrade: ''
})



const getList = async () => {
  loading.value = true
  try {
    const data = await BoxunBlockRetentionLedgerApi.getBoxunBlockRetentionLedgerPage(queryParams)
    rows.value = data.list
    total.value = Number(data.total)
  } finally {
    loading.value = false
  }
}

const handleQuery = () => {
  queryParams.pageNo = 1
  getList()
}

const resetQuery = () => {

  queryFormRef.value?.resetFields()

  handleQuery()
}

const formRef = ref()
const openForm = (type: 'create' | 'update', id?: EntityId) => {
  formRef.value?.open(type, id, type === 'create' ? undefined : undefined)
}


const detailRef = ref()
const openDetail = (id: EntityId) => {
  detailRef.value?.open(id)
}

const evaluateRef = ref()
const openEvaluate = (strengthGrade?: string) => {
  evaluateRef.value?.open(strengthGrade)
}



const handleDelete = async (id?: EntityId) => {
  if (id === undefined) return
  await message.delConfirm()
  await BoxunBlockRetentionLedgerApi.deleteBoxunBlockRetentionLedger(id)
  message.success(t('common.delSuccess'))
  await getList()
}

const checkedIds = ref<EntityId[]>([])
const handleSelectionChange = (rows: BoxunBlockRetentionLedgerRow[]) => {
  checkedIds.value = rows.map((row) => row.id).filter((id): id is EntityId => id !== undefined)
}

const handleDeleteBatch = async () => {
  await message.delConfirm()
  await BoxunBlockRetentionLedgerApi.deleteBoxunBlockRetentionLedgerList(checkedIds.value)
  message.success(t('common.delSuccess'))
  checkedIds.value = []
  await getList()
}
const exportLoading = ref(false)
const handleExport = async () => {
  await message.exportConfirm()
  exportLoading.value = true
  try {
    const data = await request.download({ url: '/boxun/block-retention-ledger/export-excel', params: queryParams })
    download.excel(data, 'boxunBlockRetentionLedger.xls')
  } finally {
    exportLoading.value = false
  }
}

/** 去委托：type 0 表示全部套件。 */
const handleEntrust = async (ids: EntityId[], type?: number) => {
  if (ids.length === 0) return
  const created = await BoxunBlockRetentionLedgerApi.entrustBoxunBlockRetentionLedger(ids, type || undefined)
  message.success(`已生成 ${created} 张委托单`)
  await getList()
}

const handleGenerateKit = async (id: EntityId, type: number) => {
  const kits = await BoxunBlockRetentionLedgerApi.generateBoxunBlockRetentionLedgerKit(id, type)
  message.success(`已生成 ${kits.length} 个套件`)
}

const handleDownloadKit = async (id: EntityId, type: number) => {
  const data = await BoxunBlockRetentionLedgerApi.downloadBoxunBlockRetentionLedgerKit(id, type)
  download.excel(data, `试块套件-${type}.xlsx`)
}

const handleTtjOrder = async (id: EntityId) => {
  const data = await BoxunBlockRetentionLedgerApi.downloadBoxunBlockRetentionLedgerTtjOrder(id)
  download.excel(data, '同养委托单.xlsx')
}

const handleCmOrder = async (id: EntityId) => {
  const data = await BoxunBlockRetentionLedgerApi.downloadBoxunBlockRetentionLedgerCmOrder(id)
  download.excel(data, '拆模委托单.xlsx')
}

onMounted(getList)
</script>
