<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看原材料进场台账" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="项目id">
        {{ detail?.projectId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="试样id">
        {{ detail?.sampleId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="委托日期">
        {{ detail?.entrustmentDate ? formatDate(new Date(detail.entrustmentDate)) : '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="进场日期">
        {{ detail?.entryDate ? formatDate(new Date(detail.entryDate)) : '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="强度等级规格牌号">
        {{ detail?.strengthGrade ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="生产厂家">
        {{ detail?.manufacturer ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="炉批号出厂编号">
        {{ detail?.furnaceBatchNumber ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="楼号">
        {{ detail?.buildingNo ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="工程部位">
        {{ detail?.concatPosition ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="代表批量">
        {{ detail?.representativeBatch ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="件数">
        {{ detail?.numberOfPieces ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="批号">
        {{ detail?.batchNumber ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="备注">
        {{ detail?.remarks ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="试验编号">
        {{ detail?.testNumber ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="检测结论">
        {{ detail?.testingConclusion ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="送样标识">
        {{ detail?.syBs ?? '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import { formatDate } from '@/utils/formatTime'
import * as BoxunRawMaterialLedgerApi from './BoxunRawMaterialLedgerApi'

type BoxunRawMaterialLedgerDetail = Awaited<ReturnType<typeof BoxunRawMaterialLedgerApi.getBoxunRawMaterialLedger>>
type EntityId = string | number

defineOptions({ name: 'BoxunRawMaterialLedgerDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunRawMaterialLedgerDetail>()

const open = async (id: EntityId) => {
  detail.value = undefined
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunRawMaterialLedgerApi.getBoxunRawMaterialLedger(id)
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
