// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunRawMaterialLedgerPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/raw-material-ledger/page', params })

export const getBoxunRawMaterialLedger = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/raw-material-ledger/get?id=' + id })

export const getBoxunRawMaterialLedgerSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/raw-material-ledger/simple-list', params })

export const listBoxunRawMaterialLedgerByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/raw-material-ledger/list-by-condition', data })

export const createBoxunRawMaterialLedger = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/raw-material-ledger/create', data })

export const upsertBoxunRawMaterialLedger = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/raw-material-ledger/upsert', data })

export const updateBoxunRawMaterialLedger = (data: EntityInput) => request.put<number>({ url: '/boxun/raw-material-ledger/update', data })

export const deleteBoxunRawMaterialLedger = (id: EntityId) => request.delete<boolean>({ url: '/boxun/raw-material-ledger/delete?id=' + id })

export const deleteBoxunRawMaterialLedgerList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/raw-material-ledger/delete-list', params: { ids: ids.join(',') } })

/** 批量新增（原 addBatch）。 */
export const addBatchBoxunRawMaterialLedger = (rows: EntityInput[]) =>
  request.post<EntityRecord[]>({ url: '/boxun/raw-material-ledger/add-batch', data: rows })

/** 原材料下拉（原 rawMaterialPullDown）。 */
export const pullDownBoxunRawMaterialLedger = (params?: Record<string, unknown>) =>
  request.get<EntityRecord[]>({ url: '/boxun/raw-material-ledger/raw-material-pull-down', params })

/** 按项目生成原材料台账（原 dataGeneration）。 */
export const generateBoxunRawMaterialLedgerData = (projectId: string) =>
  request.post<EntityRecord[]>({ url: '/boxun/raw-material-ledger/data-generation', params: { projectId } })

/** 生成各类原材料记录（原 generateVariousRawMaterialRecords）。 */
export const generateBoxunRawMaterialLedgerRecords = (ids: EntityId[]) =>
  request.post<EntityRecord[]>({
    url: '/boxun/raw-material-ledger/generate-various-raw-material-records',
    data: { ids }
  })
