// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunAccountPaymentPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/account-payment/page', params })

export const getBoxunAccountPayment = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/account-payment/get?id=' + id })

export const getBoxunAccountPaymentSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/account-payment/simple-list', params })

export const listBoxunAccountPaymentByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/account-payment/list-by-condition', data })

export const createBoxunAccountPayment = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/account-payment/create', data })

export const upsertBoxunAccountPayment = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/account-payment/upsert', data })

export const updateBoxunAccountPayment = (data: EntityInput) => request.put<number>({ url: '/boxun/account-payment/update', data })

export const deleteBoxunAccountPayment = (id: EntityId) => request.delete<boolean>({ url: '/boxun/account-payment/delete?id=' + id })

export const deleteBoxunAccountPaymentList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/account-payment/delete-list', params: { ids: ids.join(',') } })
