<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog
    v-model="dialogVisible"
    :close-on-click-modal="false"
    :title="dialogTitle"
    max-height="60vh"
    scroll
    width="min(760px, calc(100vw - 32px))"
  >
    <el-form ref="formRef" v-loading="formLoading" :model="formData" :rules="formRules" label-position="top">
<el-row class="!mx-0" :gutter="16">
        <el-col :span="12">
          <el-form-item label="用户名" prop="username">
            <el-input v-model="formData.username" placeholder="请输入用户名" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="支付金额" prop="paymentAmount">
            <el-input-number v-model="formData.paymentAmount" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="支付时间" prop="paymentTime">
            <el-date-picker v-model="formData.paymentTime" class="!w-100%" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="请选择支付时间" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="到期时间" prop="expirationTime">
            <el-date-picker v-model="formData.expirationTime" class="!w-100%" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="请选择到期时间" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="订单编号" prop="orderNumber">
            <el-input v-model="formData.orderNumber" placeholder="请输入订单编号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="账户类型" prop="accountType">
            <el-input-number v-model="formData.accountType" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="业务描述" prop="businessDescription">
            <el-input v-model="formData.businessDescription" placeholder="请输入业务描述" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="订单支付状态" prop="orderPaymentStatus">
            <el-input-number v-model="formData.orderPaymentStatus" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
</el-row>
    </el-form>

    <template #footer>
      <el-button :disabled="formLoading" type="primary" @click="submitForm">确定</el-button>
      <el-button @click="dialogVisible = false">取消</el-button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import * as BoxunAccountPaymentApi from './BoxunAccountPaymentApi'

type BoxunAccountPaymentFormData = Parameters<typeof BoxunAccountPaymentApi.createBoxunAccountPayment>[0]
type EntityId = string | number


defineOptions({ name: 'BoxunAccountPaymentForm' })

const emit = defineEmits<{ success: [] }>()
const message = useMessage()
const { t } = useI18n()
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formLoading = ref(false)
const formType = ref<'create' | 'update'>('create')
const editingId = ref<EntityId>()
const formRef = ref()
const initialFormData = () => ({
  username: '',
  paymentAmount: undefined,
  paymentTime: undefined,
  expirationTime: undefined,
  orderNumber: '',
  accountType: undefined,
  businessDescription: '',
  orderPaymentStatus: undefined
}) as BoxunAccountPaymentFormData
const formData = ref(initialFormData())
const formRules = reactive({

})






const open = async (type: 'create' | 'update', id?: EntityId, defaults?: Partial<BoxunAccountPaymentFormData>) => {

  formType.value = type
  editingId.value = id

  dialogTitle.value = type === 'create' ? '新增账户支付状态' : '修改账户支付状态'
  formData.value = { ...initialFormData(), ...defaults }
  formLoading.value = true
  dialogVisible.value = true
  try {


    if (id !== undefined) {
      formData.value = { ...initialFormData(), ...await BoxunAccountPaymentApi.getBoxunAccountPayment(id) }

    }


  } finally {
    formLoading.value = false
    await nextTick()
    formRef.value?.clearValidate()

  }
}
defineExpose({ open })


const submitForm = async () => {
  if (formLoading.value) return



  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) {

    return
  }
  const inputFields = formType.value === 'create' ? ['username', 'paymentAmount', 'paymentTime', 'expirationTime', 'orderNumber', 'accountType', 'businessDescription', 'orderPaymentStatus'] : ['id', 'username', 'paymentAmount', 'paymentTime', 'expirationTime', 'orderNumber', 'accountType', 'businessDescription', 'orderPaymentStatus']
  const input = Object.fromEntries(inputFields.map((key) => [key, formData.value[key]]))
  if ('paymentTime' in input) input.paymentTime = formData.value.paymentTime ? String(formData.value.paymentTime).replace(' ', 'T') : null
  if ('expirationTime' in input) input.expirationTime = formData.value.expirationTime ? String(formData.value.expirationTime).replace(' ', 'T') : null
  formLoading.value = true
  try {
    if (formType.value === 'create') {
      await BoxunAccountPaymentApi.createBoxunAccountPayment(input)
      message.success(t('common.createSuccess'))
    } else {
      await BoxunAccountPaymentApi.updateBoxunAccountPayment(input)
      message.success(t('common.updateSuccess'))
    }
    dialogVisible.value = false
    emit('success')
  } finally {
    formLoading.value = false
  }
}
</script>
