<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看委托单" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="试块留置台账id">
        {{ detail?.fkSkId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="原材料id">
        {{ detail?.fkYclId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="工程名称">
        {{ detail?.projectName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="工程名称及楼号">
        {{ detail?.projectNameWithLou ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="委托日期">
        {{ detail?.commissionDate ? formatDate(new Date(detail.commissionDate)) : '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="样品类型">
        {{ detail?.sampleType ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="送检单位">
        {{ detail?.inspectionDepartment ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="见证单位">
        {{ detail?.witnessUnit ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="施工单位">
        {{ detail?.constructionOrganization ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="建设单位">
        {{ detail?.developmentOrganization ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="委托人及联系电话">
        {{ detail?.clientAndContactNumber ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="见证人及联系电话">
        {{ detail?.witnessAndContactNumber ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="业务咨询电话">
        {{ detail?.businessEnquiryTelephone ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="送检单位地址">
        {{ detail?.addressOfTheInspectionUnit ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="报告编号">
        {{ detail?.reportNumber ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="材料名称">
        {{ detail?.materialName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="检验依据">
        {{ detail?.inspectionBasis ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="规范编码">
        {{ detail?.normativeEncoding ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="送样标识">
        {{ detail?.syBs ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="是否打印">
        {{ detail?.printFlag ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="附件地址">
        {{ detail?.attachmentUrl ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="附件名">
        {{ detail?.fileName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="委托备注">
        {{ detail?.wtRemarks ?? '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import { formatDate } from '@/utils/formatTime'
import * as BoxunCommissionOrderApi from './BoxunCommissionOrderApi'

type BoxunCommissionOrderDetail = Awaited<ReturnType<typeof BoxunCommissionOrderApi.getBoxunCommissionOrder>>
type EntityId = string | number

defineOptions({ name: 'BoxunCommissionOrderDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunCommissionOrderDetail>()

const open = async (id: EntityId) => {
  detail.value = undefined
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunCommissionOrderApi.getBoxunCommissionOrder(id)
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
