// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunCommissionOrderPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/commission-order/page', params })

export const getBoxunCommissionOrder = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/commission-order/get?id=' + id })

export const getBoxunCommissionOrderSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/commission-order/simple-list', params })

export const listBoxunCommissionOrderByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/commission-order/list-by-condition', data })

export const createBoxunCommissionOrder = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/commission-order/create', data })

export const upsertBoxunCommissionOrder = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/commission-order/upsert', data })

export const updateBoxunCommissionOrder = (data: EntityInput) => request.put<number>({ url: '/boxun/commission-order/update', data })

export const deleteBoxunCommissionOrder = (id: EntityId) => request.delete<boolean>({ url: '/boxun/commission-order/delete?id=' + id })

export const deleteBoxunCommissionOrderList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/commission-order/delete-list', params: { ids: ids.join(',') } })

/** 下发委托单（原 issueAnOrder）。 */
export const issueBoxunCommissionOrder = (ids: EntityId[]) =>
  request.post<boolean>({ url: '/boxun/commission-order/issue-an-order', data: { ids: ids.map((id) => String(id)) } })

/** 委托单下的样品（原 queryCommissionOrderSampleByMainId）。 */
export const queryBoxunCommissionOrderSamplesByMainId = (id: EntityId) =>
  request.get<EntityRecord[]>({ url: '/boxun/commission-order/query-commission-order-sample-by-main-id', params: { id } })

/** 生成/下载委托单附件。 */
export const downloadBoxunCommissionOrderAttachment = (id: EntityId) =>
  request.download({ url: '/boxun/commission-order/download-attachment', params: { id } })
