<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog
    v-model="dialogVisible"
    :close-on-click-modal="false"
    :title="dialogTitle"
    max-height="60vh"
    scroll
    width="min(760px, calc(100vw - 32px))"
  >
    <el-form ref="formRef" v-loading="formLoading" :model="formData" :rules="formRules" label-position="top">
<el-row class="!mx-0" :gutter="16">
        <el-col :span="12">
          <el-form-item label="试块留置台账id" prop="fkSkId">
            <el-input v-model="formData.fkSkId" placeholder="请输入试块留置台账id" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="原材料id" prop="fkYclId">
            <el-input v-model="formData.fkYclId" placeholder="请输入原材料id" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="工程名称" prop="projectName">
            <el-input v-model="formData.projectName" placeholder="请输入工程名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="工程名称及楼号" prop="projectNameWithLou">
            <el-input v-model="formData.projectNameWithLou" placeholder="请输入工程名称及楼号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="委托日期" prop="commissionDate">
            <el-date-picker v-model="formData.commissionDate" class="!w-100%" type="date" value-format="YYYY-MM-DD" placeholder="请选择委托日期" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="样品类型" prop="sampleType">
            <el-input-number v-model="formData.sampleType" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="送检单位" prop="inspectionDepartment">
            <el-input v-model="formData.inspectionDepartment" placeholder="请输入送检单位" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="见证单位" prop="witnessUnit">
            <el-input v-model="formData.witnessUnit" placeholder="请输入见证单位" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="施工单位" prop="constructionOrganization">
            <el-input v-model="formData.constructionOrganization" placeholder="请输入施工单位" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="建设单位" prop="developmentOrganization">
            <el-input v-model="formData.developmentOrganization" placeholder="请输入建设单位" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="委托人及联系电话" prop="clientAndContactNumber">
            <el-input v-model="formData.clientAndContactNumber" placeholder="请输入委托人及联系电话" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="见证人及联系电话" prop="witnessAndContactNumber">
            <el-input v-model="formData.witnessAndContactNumber" placeholder="请输入见证人及联系电话" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="业务咨询电话" prop="businessEnquiryTelephone">
            <el-input v-model="formData.businessEnquiryTelephone" placeholder="请输入业务咨询电话" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="送检单位地址" prop="addressOfTheInspectionUnit">
            <el-input v-model="formData.addressOfTheInspectionUnit" placeholder="请输入送检单位地址" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="报告编号" prop="reportNumber">
            <el-input v-model="formData.reportNumber" placeholder="请输入报告编号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="材料名称" prop="materialName">
            <el-input v-model="formData.materialName" placeholder="请输入材料名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="检验依据" prop="inspectionBasis">
            <el-input v-model="formData.inspectionBasis" placeholder="请输入检验依据" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="规范编码" prop="normativeEncoding">
            <el-input v-model="formData.normativeEncoding" placeholder="请输入规范编码" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="送样标识" prop="syBs">
            <el-input v-model="formData.syBs" placeholder="请输入送样标识" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="是否打印" prop="printFlag">
            <el-switch v-model="formData.printFlag" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="附件地址" prop="attachmentUrl">
            <el-input v-model="formData.attachmentUrl" placeholder="请输入附件地址" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="附件名" prop="fileName">
            <el-input v-model="formData.fileName" placeholder="请输入附件名" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="委托备注" prop="wtRemarks">
            <el-input v-model="formData.wtRemarks" :rows="4" placeholder="请输入委托备注" type="textarea" />
          </el-form-item>
        </el-col>
</el-row>
    </el-form>

    <template #footer>
      <el-button :disabled="formLoading" type="primary" @click="submitForm">确定</el-button>
      <el-button @click="dialogVisible = false">取消</el-button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted } from 'vue'
import * as BoxunCommissionOrderApi from './BoxunCommissionOrderApi'
import {
  currentProjectId,
  loadProjectCompanies,
  loadProjects,
  projectUnitType
} from '@/features/project/projectContext'

type BoxunCommissionOrderFormData = Parameters<typeof BoxunCommissionOrderApi.createBoxunCommissionOrder>[0]
type EntityId = string | number


defineOptions({ name: 'BoxunCommissionOrderForm' })

const emit = defineEmits<{ success: [] }>()
const message = useMessage()
const { t } = useI18n()
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formLoading = ref(false)
const formType = ref<'create' | 'update'>('create')
const editingId = ref<EntityId>()
const formRef = ref()
const initialFormData = () => ({
  projectId: currentProjectId.value,
  fkSkId: '',
  fkYclId: '',
  projectName: '',
  projectNameWithLou: '',
  commissionDate: undefined,
  sampleType: undefined,
  inspectionDepartment: '',
  witnessUnit: '',
  constructionOrganization: '',
  developmentOrganization: '',
  clientAndContactNumber: '',
  witnessAndContactNumber: '',
  businessEnquiryTelephone: '',
  addressOfTheInspectionUnit: '',
  reportNumber: '',
  materialName: '',
  inspectionBasis: '',
  normativeEncoding: '',
  syBs: '',
  printFlag: '',
  attachmentUrl: '',
  fileName: '',
  wtRemarks: ''
}) as BoxunCommissionOrderFormData
const formData = ref(initialFormData())
const formRules = reactive({

})

const firstEnabledCompanyName = (
  companies: Awaited<ReturnType<typeof loadProjectCompanies>>,
  unitType: number
) =>
  companies.find((company) => company.unitType === unitType && company.enableOrNot !== 0)?.unitName ?? ''

const applyProjectDefaults = async (force = false) => {
  const projectId = currentProjectId.value
  if (!projectId) {
    return
  }
  const [projectList, companies] = await Promise.all([loadProjects(), loadProjectCompanies(projectId)])
  const project = projectList.find((item) => String(item.id) === projectId)
  if (!project) {
    return
  }
  if (force || !formData.value.projectName) {
    formData.value.projectName = String(project.projectName ?? project.name ?? '')
  }
  if (force || !formData.value.inspectionDepartment) {
    formData.value.inspectionDepartment = firstEnabledCompanyName(companies, projectUnitType.inspection)
  }
  if (force || !formData.value.witnessUnit) {
    formData.value.witnessUnit = firstEnabledCompanyName(companies, projectUnitType.witness)
  }
  if (force || !formData.value.constructionOrganization) {
    formData.value.constructionOrganization = firstEnabledCompanyName(companies, projectUnitType.construction)
  }
  if (force || !formData.value.developmentOrganization) {
    formData.value.developmentOrganization = firstEnabledCompanyName(companies, projectUnitType.development)
  }
}

const handleProjectChanged = async () => {
  if (formType.value === 'create' && dialogVisible.value) {
    await applyProjectDefaults(true)
  }
}

onMounted(() => {
  window.addEventListener('boxun:project-changed', handleProjectChanged)
})

onBeforeUnmount(() => {
  window.removeEventListener('boxun:project-changed', handleProjectChanged)
})






const open = async (type: 'create' | 'update', id?: EntityId, defaults?: Partial<BoxunCommissionOrderFormData>) => {

  formType.value = type
  editingId.value = id

  dialogTitle.value = type === 'create' ? '新增委托单' : '修改委托单'
  formData.value = { ...initialFormData(), ...defaults }
  formLoading.value = true
  dialogVisible.value = true
  try {
    if (type === 'create') {
      await applyProjectDefaults(true)
    }


    if (id !== undefined) {
      formData.value = { ...initialFormData(), ...await BoxunCommissionOrderApi.getBoxunCommissionOrder(id) }

    }


  } finally {
    formLoading.value = false
    await nextTick()
    formRef.value?.clearValidate()

  }
}
defineExpose({ open })


const submitForm = async () => {
  if (formLoading.value) return



  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) {

    return
  }
  const inputFields = formType.value === 'create' ? ['projectId', 'fkSkId', 'fkYclId', 'projectName', 'projectNameWithLou', 'commissionDate', 'sampleType', 'inspectionDepartment', 'witnessUnit', 'constructionOrganization', 'developmentOrganization', 'clientAndContactNumber', 'witnessAndContactNumber', 'businessEnquiryTelephone', 'addressOfTheInspectionUnit', 'reportNumber', 'materialName', 'inspectionBasis', 'normativeEncoding', 'syBs', 'printFlag', 'attachmentUrl', 'fileName', 'wtRemarks'] : ['id', 'projectId', 'fkSkId', 'fkYclId', 'projectName', 'projectNameWithLou', 'commissionDate', 'sampleType', 'inspectionDepartment', 'witnessUnit', 'constructionOrganization', 'developmentOrganization', 'clientAndContactNumber', 'witnessAndContactNumber', 'businessEnquiryTelephone', 'addressOfTheInspectionUnit', 'reportNumber', 'materialName', 'inspectionBasis', 'normativeEncoding', 'syBs', 'printFlag', 'attachmentUrl', 'fileName', 'wtRemarks']
  const input = Object.fromEntries(inputFields.map((key) => [key, formData.value[key]]))
  if ('commissionDate' in input) input.commissionDate = formData.value.commissionDate ? String(formData.value.commissionDate).replace(' ', 'T') : null
  formLoading.value = true
  try {
    if (formType.value === 'create') {
      await BoxunCommissionOrderApi.createBoxunCommissionOrder(input)
      message.success(t('common.createSuccess'))
    } else {
      await BoxunCommissionOrderApi.updateBoxunCommissionOrder(input)
      message.success(t('common.updateSuccess'))
    }
    dialogVisible.value = false
    emit('success')
  } finally {
    formLoading.value = false
  }
}
</script>
