<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看见证记录" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="委托单外键">
        {{ detail?.fkWtId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="工程名称">
        {{ detail?.projectName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="编号">
        {{ detail?.number ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="样品名称">
        {{ detail?.sampleName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="试件编号">
        {{ detail?.testPieceNumber ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="取样数量">
        {{ detail?.samplingQuantity ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="楼号">
        {{ detail?.buildingNo ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="取样部位地点">
        {{ detail?.samplingLocation ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="取样日期">
        {{ detail?.samplingDate ? formatDate(new Date(detail.samplingDate)) : '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="样品及组数说明">
        {{ detail?.sampleAndGroupDescription ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="检测公司名称">
        {{ detail?.testingCompanyName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="见证取样说明">
        {{ detail?.witnessSamplingInstructions ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="是否打印">
        {{ detail?.printFlag ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="文件名称">
        {{ detail?.fileName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="附件地址">
        {{ detail?.attachmentUrl ?? '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import { formatDate } from '@/utils/formatTime'
import * as BoxunWitnessRecordApi from './BoxunWitnessRecordApi'

type BoxunWitnessRecordDetail = Awaited<ReturnType<typeof BoxunWitnessRecordApi.getBoxunWitnessRecord>>
type EntityId = string | number

defineOptions({ name: 'BoxunWitnessRecordDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunWitnessRecordDetail>()

const open = async (id: EntityId) => {
  detail.value = undefined
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunWitnessRecordApi.getBoxunWitnessRecord(id)
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
