<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog
    v-model="dialogVisible"
    :close-on-click-modal="false"
    :title="dialogTitle"
    max-height="60vh"
    scroll
    width="min(760px, calc(100vw - 32px))"
  >
    <el-form ref="formRef" v-loading="formLoading" :model="formData" :rules="formRules" label-position="top">
<el-row class="!mx-0" :gutter="16">
        <el-col :span="12">
          <el-form-item label="委托单外键" prop="fkWtId">
            <el-input v-model="formData.fkWtId" placeholder="请输入委托单外键" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="工程名称" prop="projectName">
            <el-input v-model="formData.projectName" placeholder="请输入工程名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="编号" prop="number">
            <el-input v-model="formData.number" placeholder="请输入编号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="样品名称" prop="sampleName">
            <el-input v-model="formData.sampleName" placeholder="请输入样品名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="试件编号" prop="testPieceNumber">
            <el-input v-model="formData.testPieceNumber" placeholder="请输入试件编号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="取样数量" prop="samplingQuantity">
            <el-input-number v-model="formData.samplingQuantity" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="楼号" prop="buildingNo">
            <el-input v-model="formData.buildingNo" placeholder="请输入楼号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="取样部位地点" prop="samplingLocation">
            <el-input v-model="formData.samplingLocation" placeholder="请输入取样部位地点" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="取样日期" prop="samplingDate">
            <el-date-picker v-model="formData.samplingDate" class="!w-100%" type="date" value-format="YYYY-MM-DD" placeholder="请选择取样日期" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="样品及组数说明" prop="sampleAndGroupDescription">
            <el-input v-model="formData.sampleAndGroupDescription" :rows="4" placeholder="请输入样品及组数说明" type="textarea" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="检测公司名称" prop="testingCompanyName">
            <el-input v-model="formData.testingCompanyName" placeholder="请输入检测公司名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="见证取样说明" prop="witnessSamplingInstructions">
            <el-input v-model="formData.witnessSamplingInstructions" :rows="4" placeholder="请输入见证取样说明" type="textarea" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="是否打印" prop="printFlag">
            <el-switch v-model="formData.printFlag" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="文件名称" prop="fileName">
            <el-input v-model="formData.fileName" placeholder="请输入文件名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="附件地址" prop="attachmentUrl">
            <el-input v-model="formData.attachmentUrl" placeholder="请输入附件地址" />
          </el-form-item>
        </el-col>
</el-row>
    </el-form>

    <template #footer>
      <el-button :disabled="formLoading" type="primary" @click="submitForm">确定</el-button>
      <el-button @click="dialogVisible = false">取消</el-button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import * as BoxunWitnessRecordApi from './BoxunWitnessRecordApi'

type BoxunWitnessRecordFormData = Parameters<typeof BoxunWitnessRecordApi.createBoxunWitnessRecord>[0]
type EntityId = string | number


defineOptions({ name: 'BoxunWitnessRecordForm' })

const emit = defineEmits<{ success: [] }>()
const message = useMessage()
const { t } = useI18n()
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formLoading = ref(false)
const formType = ref<'create' | 'update'>('create')
const editingId = ref<EntityId>()
const formRef = ref()
const initialFormData = () => ({
  fkWtId: '',
  projectName: '',
  number: '',
  sampleName: '',
  testPieceNumber: '',
  samplingQuantity: undefined,
  buildingNo: '',
  samplingLocation: '',
  samplingDate: undefined,
  sampleAndGroupDescription: '',
  testingCompanyName: '',
  witnessSamplingInstructions: '',
  printFlag: '',
  fileName: '',
  attachmentUrl: ''
}) as BoxunWitnessRecordFormData
const formData = ref(initialFormData())
const formRules = reactive({

})






const open = async (type: 'create' | 'update', id?: EntityId, defaults?: Partial<BoxunWitnessRecordFormData>) => {

  formType.value = type
  editingId.value = id

  dialogTitle.value = type === 'create' ? '新增见证记录' : '修改见证记录'
  formData.value = { ...initialFormData(), ...defaults }
  formLoading.value = true
  dialogVisible.value = true
  try {


    if (id !== undefined) {
      formData.value = { ...initialFormData(), ...await BoxunWitnessRecordApi.getBoxunWitnessRecord(id) }

    }


  } finally {
    formLoading.value = false
    await nextTick()
    formRef.value?.clearValidate()

  }
}
defineExpose({ open })


const submitForm = async () => {
  if (formLoading.value) return



  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) {

    return
  }
  const inputFields = formType.value === 'create' ? ['fkWtId', 'projectName', 'number', 'sampleName', 'testPieceNumber', 'samplingQuantity', 'buildingNo', 'samplingLocation', 'samplingDate', 'sampleAndGroupDescription', 'testingCompanyName', 'witnessSamplingInstructions', 'printFlag', 'fileName', 'attachmentUrl'] : ['id', 'fkWtId', 'projectName', 'number', 'sampleName', 'testPieceNumber', 'samplingQuantity', 'buildingNo', 'samplingLocation', 'samplingDate', 'sampleAndGroupDescription', 'testingCompanyName', 'witnessSamplingInstructions', 'printFlag', 'fileName', 'attachmentUrl']
  const input = Object.fromEntries(inputFields.map((key) => [key, formData.value[key]]))
  if ('samplingDate' in input) input.samplingDate = formData.value.samplingDate ? String(formData.value.samplingDate).replace(' ', 'T') : null
  formLoading.value = true
  try {
    if (formType.value === 'create') {
      await BoxunWitnessRecordApi.createBoxunWitnessRecord(input)
      message.success(t('common.createSuccess'))
    } else {
      await BoxunWitnessRecordApi.updateBoxunWitnessRecord(input)
      message.success(t('common.updateSuccess'))
    }
    dialogVisible.value = false
    emit('success')
  } finally {
    formLoading.value = false
  }
}
</script>
