<!-- generated by studio，请勿手工修改。 -->
<template>
  <ContentWrap>
    <el-form ref="queryFormRef" :inline="true" :model="queryParams" class="-mb-15px">
        <el-form-item label="工程名称" prop="projectName">
          <el-input v-model="queryParams.projectName" clearable placeholder="请输入工程名称" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="编号" prop="number">
          <el-input v-model="queryParams.number" clearable placeholder="请输入编号" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="样品名称" prop="sampleName">
          <el-input v-model="queryParams.sampleName" clearable placeholder="请输入样品名称" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="试件编号" prop="testPieceNumber">
          <el-input v-model="queryParams.testPieceNumber" clearable placeholder="请输入试件编号" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="楼号" prop="buildingNo">
          <el-input v-model="queryParams.buildingNo" clearable placeholder="请输入楼号" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="取样部位地点" prop="samplingLocation">
          <el-input v-model="queryParams.samplingLocation" clearable placeholder="请输入取样部位地点" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="检测公司名称" prop="testingCompanyName">
          <el-input v-model="queryParams.testingCompanyName" clearable placeholder="请输入检测公司名称" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="文件名称" prop="fileName">
          <el-input v-model="queryParams.fileName" clearable placeholder="请输入文件名称" @keyup.enter="handleQuery" />
        </el-form-item>
      <el-form-item>
        <el-button @click="handleQuery"><Icon class="mr-5px" icon="ep:search" />查询</el-button>
        <el-button @click="resetQuery"><Icon class="mr-5px" icon="ep:refresh" />重置</el-button>
          <el-button type="primary" @click="openForm('create')">
            <Icon class="mr-5px" icon="ep:plus" />新增
          </el-button>
          <el-button type="primary" plain @click="handleGenerateFromOrder">
            <Icon class="mr-5px" icon="ep:magic-stick" />由委托单生成
          </el-button>
          <el-button :loading="exportLoading" type="success" @click="handleExport">
            <Icon class="mr-5px" icon="ep:download" />导出
          </el-button>
          <el-button :disabled="checkedIds.length === 0" type="danger" @click="handleDeleteBatch">
            <Icon class="mr-5px" icon="ep:delete" />批量删除
          </el-button>
      </el-form-item>
    </el-form>
  </ContentWrap>

  <ContentWrap>
    <el-table v-loading="loading" :data="rows" @selection-change="handleSelectionChange">
        <el-table-column align="center" type="selection" width="55" />
      <el-table-column align="center" label="行号" width="90">
        <template #default="scope">{{ (queryParams.pageNo - 1) * queryParams.pageSize + scope.$index + 1 }}</template>
      </el-table-column>
        <el-table-column label="委托单外键" prop="fkWtId" min-width="120" show-overflow-tooltip />
        <el-table-column label="工程名称" prop="projectName" min-width="120" show-overflow-tooltip />
        <el-table-column label="编号" prop="number" min-width="120" show-overflow-tooltip />
        <el-table-column label="样品名称" prop="sampleName" min-width="120" show-overflow-tooltip />
        <el-table-column label="试件编号" prop="testPieceNumber" min-width="120" show-overflow-tooltip />
        <el-table-column label="取样数量" prop="samplingQuantity" min-width="120" show-overflow-tooltip />
        <el-table-column label="楼号" prop="buildingNo" min-width="120" show-overflow-tooltip />
        <el-table-column label="取样部位地点" prop="samplingLocation" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" :formatter="dateFormatter" label="取样日期" prop="samplingDate" width="180" />
        <el-table-column label="样品及组数说明" prop="sampleAndGroupDescription" min-width="120" show-overflow-tooltip />
        <el-table-column label="检测公司名称" prop="testingCompanyName" min-width="120" show-overflow-tooltip />
        <el-table-column label="见证取样说明" prop="witnessSamplingInstructions" min-width="120" show-overflow-tooltip />
        <el-table-column label="是否打印" prop="printFlag" min-width="120" show-overflow-tooltip />
        <el-table-column label="文件名称" prop="fileName" min-width="120" show-overflow-tooltip />
        <el-table-column label="附件地址" prop="attachmentUrl" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" fixed="right" label="操作" width="160">
          <template #default="scope">
            <el-button link type="primary" @click="openDetail(scope.row.id)">查看</el-button>
            <el-button link type="primary" @click="openForm('update', scope.row.id)">编辑</el-button>
            <el-button link type="danger" @click="handleDelete(scope.row.id)">删除</el-button>
          </template>
        </el-table-column>
    </el-table>
    <Pagination v-model:limit="queryParams.pageSize" v-model:page="queryParams.pageNo" :total="total" @pagination="getList" />
  </ContentWrap>

  <BoxunWitnessRecordForm ref="formRef" @success="getList" />
  <BoxunWitnessRecordDetail ref="detailRef" />
</template>

<script setup lang="ts">
import { dateFormatter } from '@/utils/formatTime'
import request from '@/config/axios'
import download from '@/utils/download'
import * as BoxunWitnessRecordApi from './BoxunWitnessRecordApi'
import BoxunWitnessRecordForm from './BoxunWitnessRecordForm.vue'
import BoxunWitnessRecordDetail from './BoxunWitnessRecordDetail.vue'

type BoxunWitnessRecordRow = Awaited<ReturnType<typeof BoxunWitnessRecordApi.getBoxunWitnessRecordPage>>['list'][number]
type EntityId = string | number

defineOptions({ name: 'BoxunWitnessRecord' })

const message = useMessage()
const { t } = useI18n()
const loading = ref(false)
const total = ref(0)
const rows = ref<BoxunWitnessRecordRow[]>([])
const queryFormRef = ref()
const queryParams = reactive({
  pageNo: 1,
  pageSize: 10,
  projectName: '',
  number: '',
  sampleName: '',
  testPieceNumber: '',
  buildingNo: '',
  samplingLocation: '',
  testingCompanyName: '',
  fileName: ''
})



const getList = async () => {
  loading.value = true
  try {
    const data = await BoxunWitnessRecordApi.getBoxunWitnessRecordPage(queryParams)
    rows.value = data.list
    total.value = Number(data.total)
  } finally {
    loading.value = false
  }
}

const handleQuery = () => {
  queryParams.pageNo = 1
  getList()
}

const resetQuery = () => {

  queryFormRef.value?.resetFields()

  handleQuery()
}

const formRef = ref()
const openForm = (type: 'create' | 'update', id?: EntityId) => {
  formRef.value?.open(type, id, type === 'create' ? undefined : undefined)
}


const detailRef = ref()
const openDetail = (id: EntityId) => {
  detailRef.value?.open(id)
}



const handleDelete = async (id?: EntityId) => {
  if (id === undefined) return
  await message.delConfirm()
  await BoxunWitnessRecordApi.deleteBoxunWitnessRecord(id)
  message.success(t('common.delSuccess'))
  await getList()
}

const checkedIds = ref<EntityId[]>([])
const handleSelectionChange = (rows: BoxunWitnessRecordRow[]) => {
  checkedIds.value = rows.map((row) => row.id).filter((id): id is EntityId => id !== undefined)
}

const handleDeleteBatch = async () => {
  await message.delConfirm()
  await BoxunWitnessRecordApi.deleteBoxunWitnessRecordList(checkedIds.value)
  message.success(t('common.delSuccess'))
  checkedIds.value = []
  await getList()
}
const exportLoading = ref(false)
const handleExport = async () => {
  await message.exportConfirm()
  exportLoading.value = true
  try {
    const data = await request.download({ url: '/boxun/witness-record/export-excel', params: queryParams })
    download.excel(data, 'boxunWitnessRecord.xls')
  } finally {
    exportLoading.value = false
  }
}

/** 按委托单生成见证记录。 */
const handleGenerateFromOrder = async () => {
  const { value } = await message.prompt('请输入委托单ID', '由委托单生成')
  const orderId = String(value ?? '').trim()
  if (!orderId) {
    message.warning('委托单ID不能为空')
    return
  }
  const created = await BoxunWitnessRecordApi.generateBoxunWitnessRecordFromCommissionOrder(orderId)
  message.success(created.length > 0 ? `已生成 ${created.length} 条见证记录` : '未找到对应委托单')
  await getList()
}

onMounted(getList)
</script>
