<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看历史天气" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="日期">
        {{ detail?.weatherDate ? formatDate(new Date(detail.weatherDate)) : '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="星期">
        {{ detail?.week ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="最高温">
        {{ detail?.maximumTemperature ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="最低温">
        {{ detail?.lowestTemperature ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="上午天气">
        {{ detail?.morning ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="下午天气">
        {{ detail?.afternoon ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="风力风向">
        {{ detail?.windDirection ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="空气质量指数">
        {{ detail?.airQualityIndex ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="区域">
        {{ areaName || '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import { formatDate } from '@/utils/formatTime'
import * as BoxunHistoricalWeatherApi from './BoxunHistoricalWeatherApi'

type BoxunHistoricalWeatherDetail = Awaited<ReturnType<typeof BoxunHistoricalWeatherApi.getBoxunHistoricalWeather>>
type EntityId = string | number

defineOptions({ name: 'BoxunHistoricalWeatherDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunHistoricalWeatherDetail>()
const areaName = ref('')

const open = async (id: EntityId) => {
  detail.value = undefined
  areaName.value = ''
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunHistoricalWeatherApi.getBoxunHistoricalWeather(id)
    areaName.value = await BoxunHistoricalWeatherApi.resolveBoxunHistoricalWeatherAreaName(
      detail.value?.areaId
    )
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
