<!-- generated by studio，请勿手工修改。 -->
<template>
  <ContentWrap>
    <el-form ref="queryFormRef" :inline="true" :model="queryParams" class="-mb-15px">
      <el-form-item label="区域" prop="areaKeyword">
        <el-select
          v-model="queryParams.areaKeyword"
          class="!w-260px"
          clearable
          filterable
          remote
          reserve-keyword
          :remote-method="searchAreas"
          :loading="areaLoading"
          placeholder="请输入区域名称，如 洛阳"
        >
          <el-option
            v-for="area in areaOptions"
            :key="area.areaId"
            :label="area.areaLabel"
            :value="area.areaName"
          />
        </el-select>
      </el-form-item>
      <el-form-item label="日期" prop="weatherDateRange">
        <el-date-picker
          v-model="queryParams.weatherDateRange"
          class="!w-260px"
          type="daterange"
          value-format="YYYY-MM-DD"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          @change="handleQuery"
        />
      </el-form-item>
      <el-form-item>
        <el-button @click="handleQuery"><Icon class="mr-5px" icon="ep:search" />查询</el-button>
        <el-button @click="resetQuery"><Icon class="mr-5px" icon="ep:refresh" />重置</el-button>
        <el-button type="primary" @click="openForm('create')">
          <Icon class="mr-5px" icon="ep:plus" />新增
        </el-button>
        <el-button type="primary" plain @click="handleSyncYear">
          <Icon class="mr-5px" icon="ep:refresh" />同步整年
        </el-button>
        <el-button type="warning" plain @click="handleSyncMonth">
          <Icon class="mr-5px" icon="ep:refresh" />同步当月
        </el-button>
        <el-button :loading="exportLoading" type="success" @click="handleExport">
          <Icon class="mr-5px" icon="ep:download" />导出
        </el-button>
        <el-button :disabled="checkedIds.length === 0" type="danger" @click="handleDeleteBatch">
          <Icon class="mr-5px" icon="ep:delete" />批量删除
        </el-button>
      </el-form-item>
    </el-form>
  </ContentWrap>

  <ContentWrap>
    <el-table v-loading="loading" :data="rows" @selection-change="handleSelectionChange">
      <el-table-column align="center" type="selection" width="55" />
      <el-table-column align="center" label="行号" width="90">
        <template #default="scope">{{ (queryParams.pageNo - 1) * queryParams.pageSize + scope.$index + 1 }}</template>
      </el-table-column>
      <el-table-column align="center" :formatter="dateFormatter" label="日期" prop="weatherDate" width="180" />
      <el-table-column label="星期" prop="week" min-width="100" show-overflow-tooltip />
      <el-table-column label="最高温" prop="maximumTemperature" min-width="100" show-overflow-tooltip />
      <el-table-column label="最低温" prop="lowestTemperature" min-width="100" show-overflow-tooltip />
      <el-table-column label="上午天气" prop="morning" min-width="120" show-overflow-tooltip />
      <el-table-column label="下午天气" prop="afternoon" min-width="120" show-overflow-tooltip />
      <el-table-column label="风力风向" prop="windDirection" min-width="120" show-overflow-tooltip />
      <el-table-column label="空气质量指数" prop="airQualityIndex" min-width="120" show-overflow-tooltip />
      <el-table-column label="区域" prop="areaName" min-width="140" show-overflow-tooltip />
      <el-table-column align="center" fixed="right" label="操作" width="160">
        <template #default="scope">
          <el-button link type="primary" @click="openDetail(scope.row.id)">查看</el-button>
          <el-button link type="primary" @click="openForm('update', scope.row.id)">编辑</el-button>
          <el-button link type="danger" @click="handleDelete(scope.row.id)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
    <Pagination v-model:limit="queryParams.pageSize" v-model:page="queryParams.pageNo" :total="total" @pagination="getList" />
  </ContentWrap>

  <BoxunHistoricalWeatherForm ref="formRef" @success="getList" />
  <BoxunHistoricalWeatherDetail ref="detailRef" />
</template>

<script setup lang="ts">
import { dateFormatter } from '@/utils/formatTime'
import request from '@/config/axios'
import download from '@/utils/download'
import * as BoxunHistoricalWeatherApi from './BoxunHistoricalWeatherApi'
import BoxunHistoricalWeatherForm from './BoxunHistoricalWeatherForm.vue'
import BoxunHistoricalWeatherDetail from './BoxunHistoricalWeatherDetail.vue'

type BoxunHistoricalWeatherRow = Awaited<ReturnType<typeof BoxunHistoricalWeatherApi.getBoxunHistoricalWeatherPageView>>['list'][number]
type EntityId = string | number
type WeatherAreaOption = Awaited<ReturnType<typeof BoxunHistoricalWeatherApi.searchBoxunHistoricalWeatherAreas>>[number] & {
  areaLabel: string
}

defineOptions({ name: 'BoxunHistoricalWeather' })

const message = useMessage()
const { t } = useI18n()
const loading = ref(false)
const total = ref(0)
const rows = ref<BoxunHistoricalWeatherRow[]>([])
const queryFormRef = ref()
const queryParams = reactive({
  pageNo: 1,
  pageSize: 10,
  areaKeyword: '',
  weatherDateRange: [] as string[]
})
const areaOptions = ref<WeatherAreaOption[]>([])
const areaLoading = ref(false)

const getList = async () => {
  loading.value = true
  try {
    const data = await BoxunHistoricalWeatherApi.getBoxunHistoricalWeatherPageView({
      pageNo: queryParams.pageNo,
      pageSize: queryParams.pageSize,
      areaKeyword: queryParams.areaKeyword,
      startDate: queryParams.weatherDateRange?.[0],
      endDate: queryParams.weatherDateRange?.[1]
    })
    rows.value = data.list
    total.value = Number(data.total)
  } finally {
    loading.value = false
  }
}

/** 按名称检索可选区域，展示为「省/市 名称」。 */
const searchAreas = async (keyword: string) => {
  const normalized = String(keyword ?? '').trim()
  if (!normalized) {
    areaOptions.value = []
    return
  }
  areaLoading.value = true
  try {
    const areas = await BoxunHistoricalWeatherApi.searchBoxunHistoricalWeatherAreas(normalized)
    areaOptions.value = areas.map((area) => ({
      ...area,
      areaLabel: [area.provinceName, area.cityName, area.areaName]
        .filter((part, index, list) => part && list.indexOf(part) === index)
        .join(' / ')
    }))
  } finally {
    areaLoading.value = false
  }
}

const handleQuery = () => {
  queryParams.pageNo = 1
  getList()
}

const resetQuery = () => {
  queryFormRef.value?.resetFields()
  queryParams.areaKeyword = ''
  queryParams.weatherDateRange = []
  areaOptions.value = []
  handleQuery()
}

const formRef = ref()
const openForm = (type: 'create' | 'update', id?: EntityId) => {
  formRef.value?.open(type, id, type === 'create' ? undefined : undefined)
}

const detailRef = ref()
const openDetail = (id: EntityId) => {
  detailRef.value?.open(id)
}

const handleDelete = async (id?: EntityId) => {
  if (id === undefined) return
  await message.delConfirm()
  await BoxunHistoricalWeatherApi.deleteBoxunHistoricalWeather(id)
  message.success(t('common.delSuccess'))
  await getList()
}

const checkedIds = ref<EntityId[]>([])
const handleSelectionChange = (rows: BoxunHistoricalWeatherRow[]) => {
  checkedIds.value = rows.map((row) => row.id).filter((id): id is EntityId => id !== undefined)
}

const handleDeleteBatch = async () => {
  await message.delConfirm()
  await BoxunHistoricalWeatherApi.deleteBoxunHistoricalWeatherList(checkedIds.value)
  message.success(t('common.delSuccess'))
  checkedIds.value = []
  await getList()
}
const exportLoading = ref(false)
const handleExport = async () => {
  await message.exportConfirm()
  exportLoading.value = true
  try {
    const data = await request.download({ url: '/boxun/historical-weather/export-excel', params: queryParams })
    download.excel(data, 'boxunHistoricalWeather.xls')
  } finally {
    exportLoading.value = false
  }
}

/** 按年同步历史天气。 */
const handleSyncYear = async () => {
  const { value } = await message.prompt('请输入要同步的年份', '同步整年天气')
  const year = Number(value)
  if (!Number.isInteger(year) || year < 1900 || year > 2999) {
    message.warning('年份不合法')
    return
  }
  const affected = await BoxunHistoricalWeatherApi.syncBoxunHistoricalWeatherYear(year)
  message.success(`已同步 ${affected} 条天气`)
  await getList()
}

/** 按年月同步历史天气。 */
const handleSyncMonth = async () => {
  const { value } = await message.prompt('请输入要同步的月份（格式：2026-09）', '同步当月天气')
  const matched = /^(\d{4})-(\d{1,2})$/.exec(String(value ?? '').trim())
  if (!matched) {
    message.warning('月份格式应为 YYYY-MM')
    return
  }
  const year = Number(matched[1])
  const month = Number(matched[2])
  if (month < 1 || month > 12) {
    message.warning('月份不合法')
    return
  }
  const affected = await BoxunHistoricalWeatherApi.syncBoxunHistoricalWeatherMonth(year, month)
  message.success(`已同步 ${affected} 条天气`)
  await getList()
}

onMounted(getList)
</script>
