<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看混凝土施工记录" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="商混id">
        {{ detail?.fkShId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="试块留置台账id">
        {{ detail?.fkSkId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="制作日期">
        {{ detail?.productionDate ? formatDate(new Date(detail.productionDate)) : '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="楼号">
        {{ detail?.buildingNo ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="工程部位">
        {{ detail?.concatPosition ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="浇筑部位">
        {{ detail?.pouringPosition ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="施工单位">
        {{ detail?.constructionUnit ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="合计方量">
        {{ detail?.sumVolume ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="商混站名称">
        {{ detail?.nameOfCommercialMixingStation ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="混凝土浇筑方式">
        {{ detail?.concretePouringMethod ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="震捣方法">
        {{ detail?.concreteVibrationMethod ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="设计塌落度">
        {{ detail?.designSlump ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="实测塌落度">
        {{ detail?.measuredSlump ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="标准养护组数">
        {{ detail?.numberOfStandardCuringSpecimenGroups ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="同条件养护组数">
        {{ detail?.numberOfSpecimensInTheSameCulture ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="拆模组数">
        {{ detail?.numberOfDemoldingSpecimenGroups ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="抗渗组数">
        {{ detail?.numberOfSetsOfImpermeableTestPieces ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="最高温">
        {{ detail?.maximumTemperature ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="最低温">
        {{ detail?.lowestTemperature ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="上午天气">
        {{ detail?.morning ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="下午天气">
        {{ detail?.afternoon ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="是否打印">
        {{ detail?.printFlag ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="附件地址">
        {{ detail?.attachmentUrl ?? '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import { formatDate } from '@/utils/formatTime'
import * as BoxunConcreteConstructionRecordApi from './BoxunConcreteConstructionRecordApi'

type BoxunConcreteConstructionRecordDetail = Awaited<ReturnType<typeof BoxunConcreteConstructionRecordApi.getBoxunConcreteConstructionRecord>>
type EntityId = string | number

defineOptions({ name: 'BoxunConcreteConstructionRecordDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunConcreteConstructionRecordDetail>()

const open = async (id: EntityId) => {
  detail.value = undefined
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunConcreteConstructionRecordApi.getBoxunConcreteConstructionRecord(id)
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
