// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunConcreteConstructionRecordPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/concrete-construction-record/page', params })

export const getBoxunConcreteConstructionRecord = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/concrete-construction-record/get?id=' + id })

export const getBoxunConcreteConstructionRecordSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/concrete-construction-record/simple-list', params })

export const listBoxunConcreteConstructionRecordByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/concrete-construction-record/list-by-condition', data })

export const createBoxunConcreteConstructionRecord = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/concrete-construction-record/create', data })

export const upsertBoxunConcreteConstructionRecord = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/concrete-construction-record/upsert', data })

export const updateBoxunConcreteConstructionRecord = (data: EntityInput) => request.put<number>({ url: '/boxun/concrete-construction-record/update', data })

export const deleteBoxunConcreteConstructionRecord = (id: EntityId) => request.delete<boolean>({ url: '/boxun/concrete-construction-record/delete?id=' + id })

export const deleteBoxunConcreteConstructionRecordList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/concrete-construction-record/delete-list', params: { ids: ids.join(',') } })

/** 按委托单生成混凝土施工记录。 */
export const generateBoxunConcreteConstructionRecordFromCommissionOrder = (commissionOrderId: EntityId) =>
  request.post<EntityId[]>({ url: '/boxun/concrete-construction-record/generate-from-commission-order', data: { commissionOrderId: String(commissionOrderId) } })
