<!-- generated by studio，请勿手工修改。 -->
<template>
  <ContentWrap>
    <el-form ref="queryFormRef" :inline="true" :model="queryParams" class="-mb-15px">
        <el-form-item label="楼号" prop="buildingNo">
          <el-input v-model="queryParams.buildingNo" clearable placeholder="请输入楼号" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="工程部位" prop="concatPosition">
          <el-input v-model="queryParams.concatPosition" clearable placeholder="请输入工程部位" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="浇筑部位" prop="pouringPosition">
          <el-input v-model="queryParams.pouringPosition" clearable placeholder="请输入浇筑部位" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="施工单位" prop="constructionUnit">
          <el-input v-model="queryParams.constructionUnit" clearable placeholder="请输入施工单位" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="商混站名称" prop="nameOfCommercialMixingStation">
          <el-input v-model="queryParams.nameOfCommercialMixingStation" clearable placeholder="请输入商混站名称" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="下午天气" prop="afternoon">
          <el-input v-model="queryParams.afternoon" clearable placeholder="请输入下午天气" @keyup.enter="handleQuery" />
        </el-form-item>
      <el-form-item>
        <el-button @click="handleQuery"><Icon class="mr-5px" icon="ep:search" />查询</el-button>
        <el-button @click="resetQuery"><Icon class="mr-5px" icon="ep:refresh" />重置</el-button>
          <el-button type="primary" @click="openForm('create')">
            <Icon class="mr-5px" icon="ep:plus" />新增
          </el-button>
          <el-button type="primary" plain @click="handleGenerateFromOrder">
            <Icon class="mr-5px" icon="ep:magic-stick" />由委托单生成
          </el-button>
          <el-button :loading="exportLoading" type="success" @click="handleExport">
            <Icon class="mr-5px" icon="ep:download" />导出
          </el-button>
          <el-button :disabled="checkedIds.length === 0" type="danger" @click="handleDeleteBatch">
            <Icon class="mr-5px" icon="ep:delete" />批量删除
          </el-button>
      </el-form-item>
    </el-form>
  </ContentWrap>

  <ContentWrap>
    <el-table v-loading="loading" :data="rows" @selection-change="handleSelectionChange">
        <el-table-column align="center" type="selection" width="55" />
      <el-table-column align="center" label="行号" width="90">
        <template #default="scope">{{ (queryParams.pageNo - 1) * queryParams.pageSize + scope.$index + 1 }}</template>
      </el-table-column>
        <el-table-column label="商混id" prop="fkShId" min-width="120" show-overflow-tooltip />
        <el-table-column label="试块留置台账id" prop="fkSkId" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" :formatter="dateFormatter" label="制作日期" prop="productionDate" width="180" />
        <el-table-column label="楼号" prop="buildingNo" min-width="120" show-overflow-tooltip />
        <el-table-column label="工程部位" prop="concatPosition" min-width="120" show-overflow-tooltip />
        <el-table-column label="浇筑部位" prop="pouringPosition" min-width="120" show-overflow-tooltip />
        <el-table-column label="施工单位" prop="constructionUnit" min-width="120" show-overflow-tooltip />
        <el-table-column label="合计方量" prop="sumVolume" min-width="120" show-overflow-tooltip />
        <el-table-column label="商混站名称" prop="nameOfCommercialMixingStation" min-width="120" show-overflow-tooltip />
        <el-table-column label="混凝土浇筑方式" prop="concretePouringMethod" min-width="120" show-overflow-tooltip />
        <el-table-column label="震捣方法" prop="concreteVibrationMethod" min-width="120" show-overflow-tooltip />
        <el-table-column label="设计塌落度" prop="designSlump" min-width="120" show-overflow-tooltip />
        <el-table-column label="实测塌落度" prop="measuredSlump" min-width="120" show-overflow-tooltip />
        <el-table-column label="标准养护组数" prop="numberOfStandardCuringSpecimenGroups" min-width="120" show-overflow-tooltip />
        <el-table-column label="同条件养护组数" prop="numberOfSpecimensInTheSameCulture" min-width="120" show-overflow-tooltip />
        <el-table-column label="拆模组数" prop="numberOfDemoldingSpecimenGroups" min-width="120" show-overflow-tooltip />
        <el-table-column label="抗渗组数" prop="numberOfSetsOfImpermeableTestPieces" min-width="120" show-overflow-tooltip />
        <el-table-column label="最高温" prop="maximumTemperature" min-width="120" show-overflow-tooltip />
        <el-table-column label="最低温" prop="lowestTemperature" min-width="120" show-overflow-tooltip />
        <el-table-column label="上午天气" prop="morning" min-width="120" show-overflow-tooltip />
        <el-table-column label="下午天气" prop="afternoon" min-width="120" show-overflow-tooltip />
        <el-table-column label="是否打印" prop="printFlag" min-width="120" show-overflow-tooltip />
        <el-table-column label="附件地址" prop="attachmentUrl" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" fixed="right" label="操作" width="160">
          <template #default="scope">
            <el-button link type="primary" @click="openDetail(scope.row.id)">查看</el-button>
            <el-button link type="primary" @click="openForm('update', scope.row.id)">编辑</el-button>
            <el-button link type="danger" @click="handleDelete(scope.row.id)">删除</el-button>
          </template>
        </el-table-column>
    </el-table>
    <Pagination v-model:limit="queryParams.pageSize" v-model:page="queryParams.pageNo" :total="total" @pagination="getList" />
  </ContentWrap>

  <BoxunConcreteConstructionRecordForm ref="formRef" @success="getList" />
  <BoxunConcreteConstructionRecordDetail ref="detailRef" />
</template>

<script setup lang="ts">
import { dateFormatter } from '@/utils/formatTime'
import request from '@/config/axios'
import download from '@/utils/download'
import * as BoxunConcreteConstructionRecordApi from './BoxunConcreteConstructionRecordApi'
import BoxunConcreteConstructionRecordForm from './BoxunConcreteConstructionRecordForm.vue'
import BoxunConcreteConstructionRecordDetail from './BoxunConcreteConstructionRecordDetail.vue'

type BoxunConcreteConstructionRecordRow = Awaited<ReturnType<typeof BoxunConcreteConstructionRecordApi.getBoxunConcreteConstructionRecordPage>>['list'][number]
type EntityId = string | number

defineOptions({ name: 'BoxunConcreteConstructionRecord' })

const message = useMessage()
const { t } = useI18n()
const loading = ref(false)
const total = ref(0)
const rows = ref<BoxunConcreteConstructionRecordRow[]>([])
const queryFormRef = ref()
const queryParams = reactive({
  pageNo: 1,
  pageSize: 10,
  buildingNo: '',
  concatPosition: '',
  pouringPosition: '',
  constructionUnit: '',
  nameOfCommercialMixingStation: '',
  afternoon: ''
})



const getList = async () => {
  loading.value = true
  try {
    const data = await BoxunConcreteConstructionRecordApi.getBoxunConcreteConstructionRecordPage(queryParams)
    rows.value = data.list
    total.value = Number(data.total)
  } finally {
    loading.value = false
  }
}

const handleQuery = () => {
  queryParams.pageNo = 1
  getList()
}

const resetQuery = () => {

  queryFormRef.value?.resetFields()

  handleQuery()
}

const formRef = ref()
const openForm = (type: 'create' | 'update', id?: EntityId) => {
  formRef.value?.open(type, id, type === 'create' ? undefined : undefined)
}


const detailRef = ref()
const openDetail = (id: EntityId) => {
  detailRef.value?.open(id)
}



const handleDelete = async (id?: EntityId) => {
  if (id === undefined) return
  await message.delConfirm()
  await BoxunConcreteConstructionRecordApi.deleteBoxunConcreteConstructionRecord(id)
  message.success(t('common.delSuccess'))
  await getList()
}

const checkedIds = ref<EntityId[]>([])
const handleSelectionChange = (rows: BoxunConcreteConstructionRecordRow[]) => {
  checkedIds.value = rows.map((row) => row.id).filter((id): id is EntityId => id !== undefined)
}

const handleDeleteBatch = async () => {
  await message.delConfirm()
  await BoxunConcreteConstructionRecordApi.deleteBoxunConcreteConstructionRecordList(checkedIds.value)
  message.success(t('common.delSuccess'))
  checkedIds.value = []
  await getList()
}
const exportLoading = ref(false)
const handleExport = async () => {
  await message.exportConfirm()
  exportLoading.value = true
  try {
    const data = await request.download({ url: '/boxun/concrete-construction-record/export-excel', params: queryParams })
    download.excel(data, 'boxunConcreteConstructionRecord.xls')
  } finally {
    exportLoading.value = false
  }
}

/** 按委托单生成混凝土施工记录。 */
const handleGenerateFromOrder = async () => {
  const { value } = await message.prompt('请输入委托单ID', '由委托单生成')
  const orderId = String(value ?? '').trim()
  if (!orderId) {
    message.warning('委托单ID不能为空')
    return
  }
  const created = await BoxunConcreteConstructionRecordApi.generateBoxunConcreteConstructionRecordFromCommissionOrder(orderId)
  message.success(created.length > 0 ? `已生成 ${created.length} 条混凝土施工记录` : '未找到对应委托单')
  await getList()
}

onMounted(getList)
</script>
