-- Boxun 16 张业务表；从 lib/boxun-lib 的 DDL 基线同步。
CREATE TABLE "biz_account_payment_status_table" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "username" TEXT,
  "payment_amount" NUMERIC(19, 2),
  "payment_time" TIMESTAMP,
  "expiration_time" TIMESTAMP,
  "order_number" TEXT,
  "account_type" INTEGER,
  "business_description" TEXT,
  "order_payment_status" INTEGER,
  PRIMARY KEY ("id")
);
CREATE TABLE "biz_experimental_report" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "wtd_sample_id" TEXT,
  "project_id" TEXT,
  "sample_id" TEXT,
  "commission_number" TEXT,
  "report_number" TEXT,
  "project_name" TEXT,
  "project_number" TEXT,
  "engineering_location" TEXT,
  "sample_number" TEXT,
  "sample_name" TEXT,
  "sample_name4bg" TEXT,
  "entrusting_unit" TEXT,
  "sg_unit" TEXT,
  "js_unit" TEXT,
  "witness_unit" TEXT,
  "witness" TEXT,
  "principal" TEXT,
  "sample_sender" TEXT,
  "entrustment_date" DATE,
  "test_date" DATE,
  "report_date" DATE,
  "production_date" DATE,
  "make_date" DATE,
  "representative_quantity" TEXT,
  "representative_batch" TEXT,
  "model" TEXT,
  "type" TEXT,
  "strength_grade" TEXT,
  "test_method" TEXT,
  "detection_category" TEXT,
  "description" TEXT,
  "manufacturer" TEXT,
  "quality_level" TEXT,
  "sample_quantity" TEXT,
  "attachment_url" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_bystander_record" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "fk_sh_id" TEXT,
  "fk_wt_id" TEXT,
  "key_parts_of_bystanders" TEXT,
  "construction_unit" TEXT,
  "start_time_of_side_station" TIMESTAMP,
  "end_time_of_side_station" TIMESTAMP,
  "pouring_location" TEXT,
  "number_of_carpenters" INTEGER,
  "number_of_steel_workers" INTEGER,
  "number_of_concrete_workers" INTEGER,
  "number_of_technical_personnel" INTEGER,
  "number_of_automobile_pumps" INTEGER,
  "number_of_vibrating_rods" INTEGER,
  "name_of_commercial_mixing_station" TEXT,
  "strength_grade" TEXT,
  "sum_volume" DOUBLE PRECISION,
  "number_of_standard_curing_specimen_groups" INTEGER,
  "number_of_specimens_in_the_same_culture" INTEGER,
  "number_of_demolding_specimen_groups" INTEGER,
  "number_of_sets_of_impermeable_test_pieces" INTEGER,
  "date_of_bystander" DATE,
  "print_flag" TEXT,
  "attachment_url" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_delegation_order_context" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "pid" TEXT,
  "header" TEXT,
  "material_name" TEXT,
  "inspection_basis" TEXT,
  "normative_encoding" TEXT,
  "sort_no" DOUBLE PRECISION,
  "note1" TEXT,
  "note2" TEXT,
  "note3" TEXT,
  "note4" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_historical_weather" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "weather_date" DATE,
  "week" TEXT,
  "maximum_temperature" DOUBLE PRECISION,
  "lowest_temperature" DOUBLE PRECISION,
  "morning" TEXT,
  "afternoon" TEXT,
  "wind_direction" TEXT,
  "air_quality_index" TEXT,
  "accumulated_temperature" TEXT,
  "area_id" TEXT,
  "area_type" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_mobilization_of_raw_materials" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "project_id" TEXT,
  "sample_id" TEXT,
  "entrustment_date" DATE,
  "entry_date" DATE,
  "strength_grade" TEXT,
  "manufacturer" TEXT,
  "furnace_batch_number" TEXT,
  "building_no" TEXT,
  "concat_position" TEXT,
  "representative_batch" TEXT,
  "number_of_pieces" TEXT,
  "batch_number" TEXT,
  "remarks" TEXT,
  "test_number" TEXT,
  "testing_conclusion" TEXT,
  "sy_bs" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_my_template_management" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "project_id" TEXT,
  "enable_or_not" INTEGER,
  "template_url" TEXT,
  "template_description" TEXT,
  "template_type" INTEGER,
  "bytecode_ref" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_project_conpany" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "unit_name" TEXT,
  "unit_type" INTEGER,
  "social_credit_code" TEXT,
  "address" TEXT,
  "contact_person" TEXT,
  "phone" TEXT,
  "id_card" TEXT,
  "legal_person_name" TEXT,
  "legal_person_phone" TEXT,
  "legal_person_card" TEXT,
  "company_logo" TEXT,
  "enable_or_not" INTEGER,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_project_info" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "project_name" TEXT,
  "project_type" TEXT,
  "start_date" DATE,
  "completion_date" DATE,
  "engineering_progress" INTEGER,
  "area_code" TEXT,
  "area_name" TEXT,
  "project_address" TEXT,
  "name_of_inspection_company" TEXT,
  "address_of_the_inspection_unit" TEXT,
  "email_address_of_the_inspection_unit" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_property_info" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "fk_project_id" TEXT,
  "pid" TEXT,
  "name" TEXT,
  "type" INTEGER,
  "axis" TEXT,
  "lp_index" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_witness_record" (
  "id" BIGINT NOT NULL,
  "create_time" TIMESTAMP NOT NULL,
  "update_time" TIMESTAMP,
  "updater" BIGINT,
  "creator" BIGINT,
  "fk_wt_id" TEXT,
  "project_name" TEXT,
  "sample_name" TEXT,
  "building_no" TEXT,
  "sampling_date" DATE,
  "witness_sampling_instructions" TEXT,
  "print_flag" TEXT,
  "witness" TEXT,
  "witness_unit" TEXT,
  "construction_unit" TEXT,
  "sampling_location" TEXT,
  "attachment_url" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_wtsj_block_retention_ledger" (
  "id" BIGINT NOT NULL, "create_time" TIMESTAMP NOT NULL, "update_time" TIMESTAMP, "updater" BIGINT, "creator" BIGINT,
  "fk_sh_id" TEXT, "production_date" DATE, "building_no" TEXT, "concat_position" TEXT, "strength_grade" TEXT,
  "impermeability_level" TEXT, "sum_volume" DOUBLE PRECISION, "number_of_standard_curing_specimen_groups" INTEGER,
  "number_of_specimens_in_the_same_culture" INTEGER, "number_of_demolding_specimen_groups" INTEGER,
  "number_of_sets_of_impermeable_test_pieces" INTEGER, "age" INTEGER, "testing_conclusion" TEXT, "print_flag" TEXT,
  "sample_count" INTEGER, "sample_type" TEXT, "entrustment_number" TEXT, "sy_bs" TEXT, "attachment_url" TEXT,
  "sample_status" TEXT, "qr_code" TEXT, "report_number" TEXT, "test_date" DATE, "report_date" DATE, "project_id" TEXT,
  "project_name" TEXT, "engineering_location" TEXT, "entrusting_unit" TEXT, "manufacturer" TEXT, "model" TEXT,
  "representative_quantity" TEXT, "representative_batch" TEXT, "test_method" TEXT, "detection_category" TEXT,
  "description" TEXT, "quality_level" TEXT, "principal" TEXT, "sample_sender" TEXT, "witness" TEXT, "witness_unit" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_wtsj_commercial_concrete_ledger" (
  "id" BIGINT NOT NULL, "create_time" TIMESTAMP NOT NULL, "update_time" TIMESTAMP, "updater" BIGINT, "creator" BIGINT,
  "project_id" TEXT, "material_name" TEXT, "strength_grade" TEXT, "manufacturer" TEXT, "production_date" DATE,
  "building_no" TEXT, "concat_position" TEXT, "production_quantity" DOUBLE PRECISION, "sum_volume" DOUBLE PRECISION,
  "unit_price" NUMERIC(19, 2), "order_number" TEXT, "sample_id" TEXT, "testing_conclusion" TEXT, "print_flag" TEXT,
  "sample_count" INTEGER, "sample_type" TEXT, "entrustment_number" TEXT, "sy_bs" TEXT, "attachment_url" TEXT,
  "sample_status" TEXT, "qr_code" TEXT, "report_number" TEXT, PRIMARY KEY ("id")
);
CREATE TABLE "boxun_wtsj_commission_order" (
  "id" BIGINT NOT NULL, "create_time" TIMESTAMP NOT NULL, "update_time" TIMESTAMP, "updater" BIGINT, "creator" BIGINT,
  "project_id" TEXT, "project_name" TEXT, "project_name_with_lou" TEXT, "material_name" TEXT, "inspection_department" TEXT,
  "commission_date" DATE, "inspection_basis" TEXT, "construction_organization" TEXT, "sample_type" INTEGER,
  "entrustment_number" TEXT, "sy_bs" TEXT, "fk_sk_id" TEXT, "attachment_url" TEXT, "print_flag" TEXT,
  "report_number" TEXT, "test_date" DATE, "report_date" DATE, "sample_status" TEXT, "sample_count" INTEGER,
  "sample_id" TEXT, "sample_name" TEXT, "testing_conclusion" TEXT, "manufacturer" TEXT, "model" TEXT,
  "representative_quantity" TEXT, "representative_batch" TEXT, "test_method" TEXT, PRIMARY KEY ("id")
);
CREATE TABLE "boxun_wtsj_commission_order_sample" (
  "id" BIGINT NOT NULL, "create_time" TIMESTAMP NOT NULL, "update_time" TIMESTAMP, "updater" BIGINT, "creator" BIGINT,
  "order_id" TEXT, "sample_name" TEXT, "sample_type" INTEGER, "sample_count" INTEGER, "sample_status" TEXT,
  "sample_id" TEXT, "testing_conclusion" TEXT, "attachment_url" TEXT, "print_flag" TEXT, "report_number" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "boxun_wtsj_concrete_construction_record" (
  "id" BIGINT NOT NULL, "create_time" TIMESTAMP NOT NULL, "update_time" TIMESTAMP, "updater" BIGINT, "creator" BIGINT,
  "fk_sk_id" TEXT, "production_date" DATE, "concat_position" TEXT, "pouring_position" TEXT, "construction_unit" TEXT,
  "name_of_commercial_mixing_station" TEXT, "strength_grade" TEXT, "sum_volume" DOUBLE PRECISION, "print_flag" TEXT,
  "building_no" TEXT, "weather" TEXT, "temperature" TEXT, "pouring_time" TEXT, "slump" TEXT, "sample_count" INTEGER,
  "sample_type" TEXT, "entrustment_number" TEXT, "sy_bs" TEXT, "attachment_url" TEXT, "sample_status" TEXT,
  "qr_code" TEXT, "report_number" TEXT, PRIMARY KEY ("id")
);
