// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunBystanderRecordPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/bystander-record/page', params })

export const getBoxunBystanderRecord = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/bystander-record/get?id=' + id })

export const getBoxunBystanderRecordSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/bystander-record/simple-list', params })

export const listBoxunBystanderRecordByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/bystander-record/list-by-condition', data })

export const createBoxunBystanderRecord = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/bystander-record/create', data })

export const upsertBoxunBystanderRecord = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/bystander-record/upsert', data })

export const updateBoxunBystanderRecord = (data: EntityInput) => request.put<number>({ url: '/boxun/bystander-record/update', data })

export const deleteBoxunBystanderRecord = (id: EntityId) => request.delete<boolean>({ url: '/boxun/bystander-record/delete?id=' + id })

export const deleteBoxunBystanderRecordList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/bystander-record/delete-list', params: { ids: ids.join(',') } })

/** 按委托单生成旁站记录。 */
export const generateBoxunBystanderRecordFromCommissionOrder = (commissionOrderId: EntityId) =>
  request.post<EntityId[]>({ url: '/boxun/bystander-record/generate-from-commission-order', data: { commissionOrderId: String(commissionOrderId) } })
