<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog
    v-model="dialogVisible"
    :close-on-click-modal="false"
    :title="dialogTitle"
    max-height="60vh"
    scroll
    width="min(760px, calc(100vw - 32px))"
  >
    <el-form ref="formRef" v-loading="formLoading" :model="formData" :rules="formRules" label-position="top">
<el-row class="!mx-0" :gutter="16">
        <el-col :span="12">
          <el-form-item label="商混id" prop="fkShId">
            <el-input v-model="formData.fkShId" placeholder="请输入商混id" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="委托单外键" prop="fkWtId">
            <el-input v-model="formData.fkWtId" placeholder="请输入委托单外键" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="旁站关键部位及工序" prop="keyPartsOfBystanders">
            <el-input v-model="formData.keyPartsOfBystanders" :rows="4" placeholder="请输入旁站关键部位及工序" type="textarea" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="施工单位" prop="constructionUnit">
            <el-input v-model="formData.constructionUnit" placeholder="请输入施工单位" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="旁站开始时间" prop="startTimeOfSideStation">
            <el-date-picker v-model="formData.startTimeOfSideStation" class="!w-100%" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="请选择旁站开始时间" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="旁站结束时间" prop="endTimeOfSideStation">
            <el-date-picker v-model="formData.endTimeOfSideStation" class="!w-100%" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="请选择旁站结束时间" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="浇筑部位" prop="pouringLocation">
            <el-input v-model="formData.pouringLocation" placeholder="请输入浇筑部位" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="木工人数" prop="numberOfCarpenters">
            <el-input-number v-model="formData.numberOfCarpenters" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="钢筋工人数" prop="numberOfSteelWorkers">
            <el-input-number v-model="formData.numberOfSteelWorkers" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="砼工人数" prop="numberOfConcreteWorkers">
            <el-input-number v-model="formData.numberOfConcreteWorkers" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="技术人员数" prop="numberOfTechnicalPersonnel">
            <el-input-number v-model="formData.numberOfTechnicalPersonnel" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="汽车泵台数" prop="numberOfAutomobilePumps">
            <el-input-number v-model="formData.numberOfAutomobilePumps" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="震动棒根数" prop="numberOfVibratingRods">
            <el-input-number v-model="formData.numberOfVibratingRods" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="商混站名称" prop="nameOfCommercialMixingStation">
            <el-input v-model="formData.nameOfCommercialMixingStation" placeholder="请输入商混站名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="强度等级" prop="strengthGrade">
            <el-input v-model="formData.strengthGrade" placeholder="请输入强度等级" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="合计方量" prop="sumVolume">
            <el-input-number v-model="formData.sumVolume" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="标准养护组数" prop="numberOfStandardCuringSpecimenGroups">
            <el-input-number v-model="formData.numberOfStandardCuringSpecimenGroups" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="同条件养护组数" prop="numberOfSpecimensInTheSameCulture">
            <el-input-number v-model="formData.numberOfSpecimensInTheSameCulture" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="拆模组数" prop="numberOfDemoldingSpecimenGroups">
            <el-input-number v-model="formData.numberOfDemoldingSpecimenGroups" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="抗渗组数" prop="numberOfSetsOfImpermeableTestPieces">
            <el-input-number v-model="formData.numberOfSetsOfImpermeableTestPieces" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="旁站日期" prop="dateOfBystander">
            <el-date-picker v-model="formData.dateOfBystander" class="!w-100%" type="date" value-format="YYYY-MM-DD" placeholder="请选择旁站日期" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="是否打印" prop="printFlag">
            <el-switch v-model="formData.printFlag" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="附件地址" prop="attachmentUrl">
            <el-input v-model="formData.attachmentUrl" placeholder="请输入附件地址" />
          </el-form-item>
        </el-col>
</el-row>
    </el-form>

    <template #footer>
      <el-button :disabled="formLoading" type="primary" @click="submitForm">确定</el-button>
      <el-button @click="dialogVisible = false">取消</el-button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import * as BoxunBystanderRecordApi from './BoxunBystanderRecordApi'

type BoxunBystanderRecordFormData = Parameters<typeof BoxunBystanderRecordApi.createBoxunBystanderRecord>[0]
type EntityId = string | number


defineOptions({ name: 'BoxunBystanderRecordForm' })

const emit = defineEmits<{ success: [] }>()
const message = useMessage()
const { t } = useI18n()
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formLoading = ref(false)
const formType = ref<'create' | 'update'>('create')
const editingId = ref<EntityId>()
const formRef = ref()
const initialFormData = () => ({
  fkShId: '',
  fkWtId: '',
  keyPartsOfBystanders: '',
  constructionUnit: '',
  startTimeOfSideStation: undefined,
  endTimeOfSideStation: undefined,
  pouringLocation: '',
  numberOfCarpenters: undefined,
  numberOfSteelWorkers: undefined,
  numberOfConcreteWorkers: undefined,
  numberOfTechnicalPersonnel: undefined,
  numberOfAutomobilePumps: undefined,
  numberOfVibratingRods: undefined,
  nameOfCommercialMixingStation: '',
  strengthGrade: '',
  sumVolume: undefined,
  numberOfStandardCuringSpecimenGroups: undefined,
  numberOfSpecimensInTheSameCulture: undefined,
  numberOfDemoldingSpecimenGroups: undefined,
  numberOfSetsOfImpermeableTestPieces: undefined,
  dateOfBystander: undefined,
  printFlag: '',
  attachmentUrl: ''
}) as BoxunBystanderRecordFormData
const formData = ref(initialFormData())
const formRules = reactive({

})






const open = async (type: 'create' | 'update', id?: EntityId, defaults?: Partial<BoxunBystanderRecordFormData>) => {

  formType.value = type
  editingId.value = id

  dialogTitle.value = type === 'create' ? '新增旁站记录' : '修改旁站记录'
  formData.value = { ...initialFormData(), ...defaults }
  formLoading.value = true
  dialogVisible.value = true
  try {


    if (id !== undefined) {
      formData.value = { ...initialFormData(), ...await BoxunBystanderRecordApi.getBoxunBystanderRecord(id) }

    }


  } finally {
    formLoading.value = false
    await nextTick()
    formRef.value?.clearValidate()

  }
}
defineExpose({ open })


const submitForm = async () => {
  if (formLoading.value) return



  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) {

    return
  }
  const inputFields = formType.value === 'create' ? ['fkShId', 'fkWtId', 'keyPartsOfBystanders', 'constructionUnit', 'startTimeOfSideStation', 'endTimeOfSideStation', 'pouringLocation', 'numberOfCarpenters', 'numberOfSteelWorkers', 'numberOfConcreteWorkers', 'numberOfTechnicalPersonnel', 'numberOfAutomobilePumps', 'numberOfVibratingRods', 'nameOfCommercialMixingStation', 'strengthGrade', 'sumVolume', 'numberOfStandardCuringSpecimenGroups', 'numberOfSpecimensInTheSameCulture', 'numberOfDemoldingSpecimenGroups', 'numberOfSetsOfImpermeableTestPieces', 'dateOfBystander', 'printFlag', 'attachmentUrl'] : ['id', 'fkShId', 'fkWtId', 'keyPartsOfBystanders', 'constructionUnit', 'startTimeOfSideStation', 'endTimeOfSideStation', 'pouringLocation', 'numberOfCarpenters', 'numberOfSteelWorkers', 'numberOfConcreteWorkers', 'numberOfTechnicalPersonnel', 'numberOfAutomobilePumps', 'numberOfVibratingRods', 'nameOfCommercialMixingStation', 'strengthGrade', 'sumVolume', 'numberOfStandardCuringSpecimenGroups', 'numberOfSpecimensInTheSameCulture', 'numberOfDemoldingSpecimenGroups', 'numberOfSetsOfImpermeableTestPieces', 'dateOfBystander', 'printFlag', 'attachmentUrl']
  const input = Object.fromEntries(inputFields.map((key) => [key, formData.value[key]]))
  if ('startTimeOfSideStation' in input) input.startTimeOfSideStation = formData.value.startTimeOfSideStation ? String(formData.value.startTimeOfSideStation).replace(' ', 'T') : null
  if ('endTimeOfSideStation' in input) input.endTimeOfSideStation = formData.value.endTimeOfSideStation ? String(formData.value.endTimeOfSideStation).replace(' ', 'T') : null
  if ('dateOfBystander' in input) input.dateOfBystander = formData.value.dateOfBystander ? String(formData.value.dateOfBystander).replace(' ', 'T') : null
  formLoading.value = true
  try {
    if (formType.value === 'create') {
      await BoxunBystanderRecordApi.createBoxunBystanderRecord(input)
      message.success(t('common.createSuccess'))
    } else {
      await BoxunBystanderRecordApi.updateBoxunBystanderRecord(input)
      message.success(t('common.updateSuccess'))
    }
    dialogVisible.value = false
    emit('success')
  } finally {
    formLoading.value = false
  }
}
</script>
