<!-- generated by studio，请勿手工修改。 -->
<template>
  <ContentWrap>
    <el-form ref="queryFormRef" :inline="true" :model="queryParams" class="-mb-15px">
        <el-form-item label="施工单位" prop="constructionUnit">
          <el-input v-model="queryParams.constructionUnit" clearable placeholder="请输入施工单位" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="浇筑部位" prop="pouringLocation">
          <el-input v-model="queryParams.pouringLocation" clearable placeholder="请输入浇筑部位" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="商混站名称" prop="nameOfCommercialMixingStation">
          <el-input v-model="queryParams.nameOfCommercialMixingStation" clearable placeholder="请输入商混站名称" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="强度等级" prop="strengthGrade">
          <el-input v-model="queryParams.strengthGrade" clearable placeholder="请输入强度等级" @keyup.enter="handleQuery" />
        </el-form-item>
      <el-form-item>
        <el-button @click="handleQuery"><Icon class="mr-5px" icon="ep:search" />查询</el-button>
        <el-button @click="resetQuery"><Icon class="mr-5px" icon="ep:refresh" />重置</el-button>
          <el-button type="primary" @click="openForm('create')">
            <Icon class="mr-5px" icon="ep:plus" />新增
          </el-button>
          <el-button type="primary" plain @click="handleGenerateFromOrder">
            <Icon class="mr-5px" icon="ep:magic-stick" />由委托单生成
          </el-button>
          <el-button :loading="exportLoading" type="success" @click="handleExport">
            <Icon class="mr-5px" icon="ep:download" />导出
          </el-button>
          <el-button :disabled="checkedIds.length === 0" type="danger" @click="handleDeleteBatch">
            <Icon class="mr-5px" icon="ep:delete" />批量删除
          </el-button>
      </el-form-item>
    </el-form>
  </ContentWrap>

  <ContentWrap>
    <el-table v-loading="loading" :data="rows" @selection-change="handleSelectionChange">
        <el-table-column align="center" type="selection" width="55" />
      <el-table-column align="center" label="行号" width="90">
        <template #default="scope">{{ (queryParams.pageNo - 1) * queryParams.pageSize + scope.$index + 1 }}</template>
      </el-table-column>
        <el-table-column label="商混id" prop="fkShId" min-width="120" show-overflow-tooltip />
        <el-table-column label="委托单外键" prop="fkWtId" min-width="120" show-overflow-tooltip />
        <el-table-column label="旁站关键部位及工序" prop="keyPartsOfBystanders" min-width="120" show-overflow-tooltip />
        <el-table-column label="施工单位" prop="constructionUnit" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" :formatter="dateFormatter" label="旁站开始时间" prop="startTimeOfSideStation" width="180" />
        <el-table-column align="center" :formatter="dateFormatter" label="旁站结束时间" prop="endTimeOfSideStation" width="180" />
        <el-table-column label="浇筑部位" prop="pouringLocation" min-width="120" show-overflow-tooltip />
        <el-table-column label="木工人数" prop="numberOfCarpenters" min-width="120" show-overflow-tooltip />
        <el-table-column label="钢筋工人数" prop="numberOfSteelWorkers" min-width="120" show-overflow-tooltip />
        <el-table-column label="砼工人数" prop="numberOfConcreteWorkers" min-width="120" show-overflow-tooltip />
        <el-table-column label="技术人员数" prop="numberOfTechnicalPersonnel" min-width="120" show-overflow-tooltip />
        <el-table-column label="汽车泵台数" prop="numberOfAutomobilePumps" min-width="120" show-overflow-tooltip />
        <el-table-column label="震动棒根数" prop="numberOfVibratingRods" min-width="120" show-overflow-tooltip />
        <el-table-column label="商混站名称" prop="nameOfCommercialMixingStation" min-width="120" show-overflow-tooltip />
        <el-table-column label="强度等级" prop="strengthGrade" min-width="120" show-overflow-tooltip />
        <el-table-column label="合计方量" prop="sumVolume" min-width="120" show-overflow-tooltip />
        <el-table-column label="标准养护组数" prop="numberOfStandardCuringSpecimenGroups" min-width="120" show-overflow-tooltip />
        <el-table-column label="同条件养护组数" prop="numberOfSpecimensInTheSameCulture" min-width="120" show-overflow-tooltip />
        <el-table-column label="拆模组数" prop="numberOfDemoldingSpecimenGroups" min-width="120" show-overflow-tooltip />
        <el-table-column label="抗渗组数" prop="numberOfSetsOfImpermeableTestPieces" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" :formatter="dateFormatter" label="旁站日期" prop="dateOfBystander" width="180" />
        <el-table-column label="是否打印" prop="printFlag" min-width="120" show-overflow-tooltip />
        <el-table-column label="附件地址" prop="attachmentUrl" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" fixed="right" label="操作" width="160">
          <template #default="scope">
            <el-button link type="primary" @click="openDetail(scope.row.id)">查看</el-button>
            <el-button link type="primary" @click="openForm('update', scope.row.id)">编辑</el-button>
            <el-button link type="danger" @click="handleDelete(scope.row.id)">删除</el-button>
          </template>
        </el-table-column>
    </el-table>
    <Pagination v-model:limit="queryParams.pageSize" v-model:page="queryParams.pageNo" :total="total" @pagination="getList" />
  </ContentWrap>

  <BoxunBystanderRecordForm ref="formRef" @success="getList" />
  <BoxunBystanderRecordDetail ref="detailRef" />
</template>

<script setup lang="ts">
import { dateFormatter } from '@/utils/formatTime'
import request from '@/config/axios'
import download from '@/utils/download'
import * as BoxunBystanderRecordApi from './BoxunBystanderRecordApi'
import BoxunBystanderRecordForm from './BoxunBystanderRecordForm.vue'
import BoxunBystanderRecordDetail from './BoxunBystanderRecordDetail.vue'

type BoxunBystanderRecordRow = Awaited<ReturnType<typeof BoxunBystanderRecordApi.getBoxunBystanderRecordPage>>['list'][number]
type EntityId = string | number

defineOptions({ name: 'BoxunBystanderRecord' })

const message = useMessage()
const { t } = useI18n()
const loading = ref(false)
const total = ref(0)
const rows = ref<BoxunBystanderRecordRow[]>([])
const queryFormRef = ref()
const queryParams = reactive({
  pageNo: 1,
  pageSize: 10,
  constructionUnit: '',
  pouringLocation: '',
  nameOfCommercialMixingStation: '',
  strengthGrade: ''
})



const getList = async () => {
  loading.value = true
  try {
    const data = await BoxunBystanderRecordApi.getBoxunBystanderRecordPage(queryParams)
    rows.value = data.list
    total.value = Number(data.total)
  } finally {
    loading.value = false
  }
}

const handleQuery = () => {
  queryParams.pageNo = 1
  getList()
}

const resetQuery = () => {

  queryFormRef.value?.resetFields()

  handleQuery()
}

const formRef = ref()
const openForm = (type: 'create' | 'update', id?: EntityId) => {
  formRef.value?.open(type, id, type === 'create' ? undefined : undefined)
}


const detailRef = ref()
const openDetail = (id: EntityId) => {
  detailRef.value?.open(id)
}



const handleDelete = async (id?: EntityId) => {
  if (id === undefined) return
  await message.delConfirm()
  await BoxunBystanderRecordApi.deleteBoxunBystanderRecord(id)
  message.success(t('common.delSuccess'))
  await getList()
}

const checkedIds = ref<EntityId[]>([])
const handleSelectionChange = (rows: BoxunBystanderRecordRow[]) => {
  checkedIds.value = rows.map((row) => row.id).filter((id): id is EntityId => id !== undefined)
}

const handleDeleteBatch = async () => {
  await message.delConfirm()
  await BoxunBystanderRecordApi.deleteBoxunBystanderRecordList(checkedIds.value)
  message.success(t('common.delSuccess'))
  checkedIds.value = []
  await getList()
}
const exportLoading = ref(false)
const handleExport = async () => {
  await message.exportConfirm()
  exportLoading.value = true
  try {
    const data = await request.download({ url: '/boxun/bystander-record/export-excel', params: queryParams })
    download.excel(data, 'boxunBystanderRecord.xls')
  } finally {
    exportLoading.value = false
  }
}

/** 按委托单生成旁站记录。 */
const handleGenerateFromOrder = async () => {
  const { value } = await message.prompt('请输入委托单ID', '由委托单生成')
  const orderId = String(value ?? '').trim()
  if (!orderId) {
    message.warning('委托单ID不能为空')
    return
  }
  const created = await BoxunBystanderRecordApi.generateBoxunBystanderRecordFromCommissionOrder(orderId)
  message.success(created.length > 0 ? `已生成 ${created.length} 条旁站记录` : '未找到对应委托单')
  await getList()
}

onMounted(getList)
</script>
