<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog
    v-model="dialogVisible"
    :close-on-click-modal="false"
    :title="dialogTitle"
    max-height="60vh"
    scroll
    width="min(760px, calc(100vw - 32px))"
  >
    <el-form ref="formRef" v-loading="formLoading" :model="formData" :rules="formRules" label-position="top">
<el-row class="!mx-0" :gutter="16">
        <el-col :span="12">
          <el-form-item label="项目id" prop="fkProjectId">
            <el-input v-model="formData.fkProjectId" placeholder="请输入项目id" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="父id" prop="pid">
            <el-input v-model="formData.pid" placeholder="请输入父id" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="名称" prop="name">
            <el-input v-model="formData.name" placeholder="请输入名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="节点类型" prop="type">
            <el-input-number v-model="formData.type" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="轴线" prop="axis">
            <el-input v-model="formData.axis" placeholder="请输入轴线" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="排序索引" prop="lpIndex">
            <el-input v-model="formData.lpIndex" placeholder="请输入排序索引" />
          </el-form-item>
        </el-col>
</el-row>
    </el-form>

    <template #footer>
      <el-button :disabled="formLoading" type="primary" @click="submitForm">确定</el-button>
      <el-button @click="dialogVisible = false">取消</el-button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import * as BoxunPropertyInfoApi from './BoxunPropertyInfoApi'

type BoxunPropertyInfoFormData = Parameters<typeof BoxunPropertyInfoApi.createBoxunPropertyInfo>[0]
type EntityId = string | number


defineOptions({ name: 'BoxunPropertyInfoForm' })

const emit = defineEmits<{ success: [] }>()
const message = useMessage()
const { t } = useI18n()
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formLoading = ref(false)
const formType = ref<'create' | 'update'>('create')
const editingId = ref<EntityId>()
const formRef = ref()
const initialFormData = () => ({
  fkProjectId: '',
  pid: '',
  name: '',
  type: undefined,
  axis: '',
  lpIndex: ''
}) as BoxunPropertyInfoFormData
const formData = ref(initialFormData())
const formRules = reactive({

})






const open = async (type: 'create' | 'update', id?: EntityId, defaults?: Partial<BoxunPropertyInfoFormData>) => {

  formType.value = type
  editingId.value = id

  dialogTitle.value = type === 'create' ? '新增楼盘信息' : '修改楼盘信息'
  formData.value = { ...initialFormData(), ...defaults }
  formLoading.value = true
  dialogVisible.value = true
  try {


    if (id !== undefined) {
      formData.value = { ...initialFormData(), ...await BoxunPropertyInfoApi.getBoxunPropertyInfo(id) }

    }


  } finally {
    formLoading.value = false
    await nextTick()
    formRef.value?.clearValidate()

  }
}
defineExpose({ open })


const submitForm = async () => {
  if (formLoading.value) return



  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) {

    return
  }
  const inputFields = formType.value === 'create' ? ['fkProjectId', 'pid', 'name', 'type', 'axis', 'lpIndex'] : ['id', 'fkProjectId', 'pid', 'name', 'type', 'axis', 'lpIndex']
  const input = Object.fromEntries(inputFields.map((key) => [key, formData.value[key]]))

  formLoading.value = true
  try {
    if (formType.value === 'create') {
      await BoxunPropertyInfoApi.createBoxunPropertyInfo(input)
      message.success(t('common.createSuccess'))
    } else {
      await BoxunPropertyInfoApi.updateBoxunPropertyInfo(input)
      message.success(t('common.updateSuccess'))
    }
    dialogVisible.value = false
    emit('success')
  } finally {
    formLoading.value = false
  }
}
</script>
