// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunPropertyInfoPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/property-info/page', params })

export const getBoxunPropertyInfo = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/property-info/get?id=' + id })

export const getBoxunPropertyInfoSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/property-info/simple-list', params })

export const listBoxunPropertyInfoByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/property-info/list-by-condition', data })

export const createBoxunPropertyInfo = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/property-info/create', data })

export const upsertBoxunPropertyInfo = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/property-info/upsert', data })

export const updateBoxunPropertyInfo = (data: EntityInput) => request.put<number>({ url: '/boxun/property-info/update', data })

export const deleteBoxunPropertyInfo = (id: EntityId) => request.delete<boolean>({ url: '/boxun/property-info/delete?id=' + id })

export const deleteBoxunPropertyInfoList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/property-info/delete-list', params: { ids: ids.join(',') } })
