<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看楼盘信息" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="项目id">
        {{ detail?.fkProjectId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="父id">
        {{ detail?.pid ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="名称">
        {{ detail?.name ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="节点类型">
        {{ detail?.type ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="轴线">
        {{ detail?.axis ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="排序索引">
        {{ detail?.lpIndex ?? '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import * as BoxunPropertyInfoApi from './BoxunPropertyInfoApi'

type BoxunPropertyInfoDetail = Awaited<ReturnType<typeof BoxunPropertyInfoApi.getBoxunPropertyInfo>>
type EntityId = string | number

defineOptions({ name: 'BoxunPropertyInfoDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunPropertyInfoDetail>()

const open = async (id: EntityId) => {
  detail.value = undefined
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunPropertyInfoApi.getBoxunPropertyInfo(id)
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
