<!-- generated by studio，请勿手工修改。 -->
<template>
  <ContentWrap>
    <el-form ref="queryFormRef" :inline="true" :model="queryParams" class="-mb-15px">
        <el-form-item label="名称" prop="name">
          <el-input v-model="queryParams.name" clearable placeholder="请输入名称" @keyup.enter="handleQuery" />
        </el-form-item>
      <el-form-item>
        <el-button @click="handleQuery"><Icon class="mr-5px" icon="ep:search" />查询</el-button>
        <el-button @click="resetQuery"><Icon class="mr-5px" icon="ep:refresh" />重置</el-button>
          <el-button type="primary" @click="openForm('create')">
            <Icon class="mr-5px" icon="ep:plus" />新增
          </el-button>
          <el-button :loading="exportLoading" type="success" @click="handleExport">
            <Icon class="mr-5px" icon="ep:download" />导出
          </el-button>
          <el-button :disabled="checkedIds.length === 0" type="danger" @click="handleDeleteBatch">
            <Icon class="mr-5px" icon="ep:delete" />批量删除
          </el-button>
      </el-form-item>
    </el-form>
  </ContentWrap>

  <ContentWrap>
    <el-table v-loading="loading" :data="rows" @selection-change="handleSelectionChange">
        <el-table-column align="center" type="selection" width="55" />
      <el-table-column align="center" label="行号" width="90">
        <template #default="scope">{{ (queryParams.pageNo - 1) * queryParams.pageSize + scope.$index + 1 }}</template>
      </el-table-column>
        <el-table-column label="项目id" prop="fkProjectId" min-width="120" show-overflow-tooltip />
        <el-table-column label="父id" prop="pid" min-width="120" show-overflow-tooltip />
        <el-table-column label="名称" prop="name" min-width="120" show-overflow-tooltip />
        <el-table-column label="节点类型" prop="type" min-width="120" show-overflow-tooltip />
        <el-table-column label="轴线" prop="axis" min-width="120" show-overflow-tooltip />
        <el-table-column label="排序索引" prop="lpIndex" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" fixed="right" label="操作" width="160">
          <template #default="scope">
            <el-button link type="primary" @click="openDetail(scope.row.id)">查看</el-button>
            <el-button link type="primary" @click="openForm('update', scope.row.id)">编辑</el-button>
            <el-button link type="danger" @click="handleDelete(scope.row.id)">删除</el-button>
          </template>
        </el-table-column>
    </el-table>
    <Pagination v-model:limit="queryParams.pageSize" v-model:page="queryParams.pageNo" :total="total" @pagination="getList" />
  </ContentWrap>

  <BoxunPropertyInfoForm ref="formRef" @success="getList" />
  <BoxunPropertyInfoDetail ref="detailRef" />
</template>

<script setup lang="ts">
import request from '@/config/axios'
import download from '@/utils/download'
import * as BoxunPropertyInfoApi from './BoxunPropertyInfoApi'
import BoxunPropertyInfoForm from './BoxunPropertyInfoForm.vue'
import BoxunPropertyInfoDetail from './BoxunPropertyInfoDetail.vue'

type BoxunPropertyInfoRow = Awaited<ReturnType<typeof BoxunPropertyInfoApi.getBoxunPropertyInfoPage>>['list'][number]
type EntityId = string | number

defineOptions({ name: 'BoxunPropertyInfo' })

const message = useMessage()
const { t } = useI18n()
const loading = ref(false)
const total = ref(0)
const rows = ref<BoxunPropertyInfoRow[]>([])
const queryFormRef = ref()
const queryParams = reactive({
  pageNo: 1,
  pageSize: 10,
  name: ''
})



const getList = async () => {
  loading.value = true
  try {
    const data = await BoxunPropertyInfoApi.getBoxunPropertyInfoPage(queryParams)
    rows.value = data.list
    total.value = Number(data.total)
  } finally {
    loading.value = false
  }
}

const handleQuery = () => {
  queryParams.pageNo = 1
  getList()
}

const resetQuery = () => {

  queryFormRef.value?.resetFields()

  handleQuery()
}

const formRef = ref()
const openForm = (type: 'create' | 'update', id?: EntityId) => {
  formRef.value?.open(type, id, type === 'create' ? undefined : undefined)
}


const detailRef = ref()
const openDetail = (id: EntityId) => {
  detailRef.value?.open(id)
}



const handleDelete = async (id?: EntityId) => {
  if (id === undefined) return
  await message.delConfirm()
  await BoxunPropertyInfoApi.deleteBoxunPropertyInfo(id)
  message.success(t('common.delSuccess'))
  await getList()
}

const checkedIds = ref<EntityId[]>([])
const handleSelectionChange = (rows: BoxunPropertyInfoRow[]) => {
  checkedIds.value = rows.map((row) => row.id).filter((id): id is EntityId => id !== undefined)
}

const handleDeleteBatch = async () => {
  await message.delConfirm()
  await BoxunPropertyInfoApi.deleteBoxunPropertyInfoList(checkedIds.value)
  message.success(t('common.delSuccess'))
  checkedIds.value = []
  await getList()
}
const exportLoading = ref(false)
const handleExport = async () => {
  await message.exportConfirm()
  exportLoading.value = true
  try {
    const data = await request.download({ url: '/boxun/property-info/export-excel', params: queryParams })
    download.excel(data, 'boxunPropertyInfo.xls')
  } finally {
    exportLoading.value = false
  }
}

onMounted(getList)
</script>
