<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog
    v-model="dialogVisible"
    :close-on-click-modal="false"
    :title="dialogTitle"
    max-height="60vh"
    scroll
    width="min(760px, calc(100vw - 32px))"
  >
    <el-form ref="formRef" v-loading="formLoading" :model="formData" :rules="formRules" label-position="top">
<el-row class="!mx-0" :gutter="16">
        <el-col :span="12">
          <el-form-item label="项目id" prop="fkProjectId">
            <el-input v-model="formData.fkProjectId" placeholder="请输入项目id" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="浇筑日期" prop="productionDate">
            <el-date-picker v-model="formData.productionDate" class="!w-100%" type="date" value-format="YYYY-MM-DD" placeholder="请选择浇筑日期" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="楼号" prop="buildingNo">
            <el-input v-model="formData.buildingNo" placeholder="请输入楼号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="工程部位" prop="concatPosition">
            <el-input v-model="formData.concatPosition" placeholder="请输入工程部位" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="商混站名称" prop="nameOfCommercialMixingStation">
            <el-input v-model="formData.nameOfCommercialMixingStation" placeholder="请输入商混站名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="强度等级" prop="strengthGrade">
            <el-input v-model="formData.strengthGrade" placeholder="请输入强度等级" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="抗渗等级" prop="impermeabilityLevel">
            <el-input v-model="formData.impermeabilityLevel" placeholder="请输入抗渗等级" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="强度备注" prop="strengthRemarks">
            <el-input v-model="formData.strengthRemarks" placeholder="请输入强度备注" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="浇筑方量" prop="sumVolume">
            <el-input-number v-model="formData.sumVolume" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="标养试件组数" prop="numberOfStandardCuringSpecimenGroups">
            <el-input-number v-model="formData.numberOfStandardCuringSpecimenGroups" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="抗渗试件组数" prop="numberOfSetsOfImpermeableTestPieces">
            <el-input-number v-model="formData.numberOfSetsOfImpermeableTestPieces" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="同养试件组数" prop="numberOfSpecimensInTheSameCulture">
            <el-input-number v-model="formData.numberOfSpecimensInTheSameCulture" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="拆模试件组数" prop="numberOfDemoldingSpecimenGroups">
            <el-input-number v-model="formData.numberOfDemoldingSpecimenGroups" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="同养温度" prop="syntrophicTemperature">
            <el-input-number v-model="formData.syntrophicTemperature" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="随车资料" prop="accompanyingDocuments">
            <el-input v-model="formData.accompanyingDocuments" placeholder="请输入随车资料" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="28天资料" prop="day28Data">
            <el-input v-model="formData.day28Data" placeholder="请输入28天资料" />
          </el-form-item>
        </el-col>
</el-row>
    </el-form>

    <template #footer>
      <el-button :disabled="formLoading" type="primary" @click="submitForm">确定</el-button>
      <el-button @click="dialogVisible = false">取消</el-button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import * as BoxunCommercialConcreteLedgerApi from './BoxunCommercialConcreteLedgerApi'

type BoxunCommercialConcreteLedgerFormData = Parameters<typeof BoxunCommercialConcreteLedgerApi.createBoxunCommercialConcreteLedger>[0]
type EntityId = string | number


defineOptions({ name: 'BoxunCommercialConcreteLedgerForm' })

const emit = defineEmits<{ success: [] }>()
const message = useMessage()
const { t } = useI18n()
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formLoading = ref(false)
const formType = ref<'create' | 'update'>('create')
const editingId = ref<EntityId>()
const formRef = ref()
const initialFormData = () => ({
  fkProjectId: '',
  productionDate: undefined,
  buildingNo: '',
  concatPosition: '',
  nameOfCommercialMixingStation: '',
  strengthGrade: '',
  impermeabilityLevel: '',
  strengthRemarks: '',
  sumVolume: undefined,
  numberOfStandardCuringSpecimenGroups: undefined,
  numberOfSetsOfImpermeableTestPieces: undefined,
  numberOfSpecimensInTheSameCulture: undefined,
  numberOfDemoldingSpecimenGroups: undefined,
  syntrophicTemperature: undefined,
  accompanyingDocuments: '',
  day28Data: ''
}) as BoxunCommercialConcreteLedgerFormData
const formData = ref(initialFormData())
const formRules = reactive({

})






const open = async (type: 'create' | 'update', id?: EntityId, defaults?: Partial<BoxunCommercialConcreteLedgerFormData>) => {

  formType.value = type
  editingId.value = id

  dialogTitle.value = type === 'create' ? '新增商混台账' : '修改商混台账'
  formData.value = { ...initialFormData(), ...defaults }
  formLoading.value = true
  dialogVisible.value = true
  try {


    if (id !== undefined) {
      formData.value = { ...initialFormData(), ...await BoxunCommercialConcreteLedgerApi.getBoxunCommercialConcreteLedger(id) }

    }


  } finally {
    formLoading.value = false
    await nextTick()
    formRef.value?.clearValidate()

  }
}
defineExpose({ open })


const submitForm = async () => {
  if (formLoading.value) return



  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) {

    return
  }
  const inputFields = formType.value === 'create' ? ['fkProjectId', 'productionDate', 'buildingNo', 'concatPosition', 'nameOfCommercialMixingStation', 'strengthGrade', 'impermeabilityLevel', 'strengthRemarks', 'sumVolume', 'numberOfStandardCuringSpecimenGroups', 'numberOfSetsOfImpermeableTestPieces', 'numberOfSpecimensInTheSameCulture', 'numberOfDemoldingSpecimenGroups', 'syntrophicTemperature', 'accompanyingDocuments', 'day28Data'] : ['id', 'fkProjectId', 'productionDate', 'buildingNo', 'concatPosition', 'nameOfCommercialMixingStation', 'strengthGrade', 'impermeabilityLevel', 'strengthRemarks', 'sumVolume', 'numberOfStandardCuringSpecimenGroups', 'numberOfSetsOfImpermeableTestPieces', 'numberOfSpecimensInTheSameCulture', 'numberOfDemoldingSpecimenGroups', 'syntrophicTemperature', 'accompanyingDocuments', 'day28Data']
  const input = Object.fromEntries(inputFields.map((key) => [key, formData.value[key]]))
  if ('productionDate' in input) input.productionDate = formData.value.productionDate ? String(formData.value.productionDate).replace(' ', 'T') : null
  formLoading.value = true
  try {
    if (formType.value === 'create') {
      await BoxunCommercialConcreteLedgerApi.createBoxunCommercialConcreteLedger(input)
      message.success(t('common.createSuccess'))
    } else {
      await BoxunCommercialConcreteLedgerApi.updateBoxunCommercialConcreteLedger(input)
      message.success(t('common.updateSuccess'))
    }
    dialogVisible.value = false
    emit('success')
  } finally {
    formLoading.value = false
  }
}
</script>
