<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看商混台账" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="项目id">
        {{ detail?.fkProjectId ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="浇筑日期">
        {{ detail?.productionDate ? formatDate(new Date(detail.productionDate)) : '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="楼号">
        {{ detail?.buildingNo ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="工程部位">
        {{ detail?.concatPosition ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="商混站名称">
        {{ detail?.nameOfCommercialMixingStation ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="强度等级">
        {{ detail?.strengthGrade ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="抗渗等级">
        {{ detail?.impermeabilityLevel ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="强度备注">
        {{ detail?.strengthRemarks ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="浇筑方量">
        {{ detail?.sumVolume ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="标养试件组数">
        {{ detail?.numberOfStandardCuringSpecimenGroups ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="抗渗试件组数">
        {{ detail?.numberOfSetsOfImpermeableTestPieces ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="同养试件组数">
        {{ detail?.numberOfSpecimensInTheSameCulture ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="拆模试件组数">
        {{ detail?.numberOfDemoldingSpecimenGroups ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="同养温度">
        {{ detail?.syntrophicTemperature ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="随车资料">
        {{ detail?.accompanyingDocuments ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="28天资料">
        {{ detail?.day28Data ?? '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import { formatDate } from '@/utils/formatTime'
import * as BoxunCommercialConcreteLedgerApi from './BoxunCommercialConcreteLedgerApi'

type BoxunCommercialConcreteLedgerDetail = Awaited<ReturnType<typeof BoxunCommercialConcreteLedgerApi.getBoxunCommercialConcreteLedger>>
type EntityId = string | number

defineOptions({ name: 'BoxunCommercialConcreteLedgerDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunCommercialConcreteLedgerDetail>()

const open = async (id: EntityId) => {
  detail.value = undefined
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunCommercialConcreteLedgerApi.getBoxunCommercialConcreteLedger(id)
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
