// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunCommercialConcreteLedgerPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/commercial-concrete-ledger/page', params })

export const getBoxunCommercialConcreteLedger = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/commercial-concrete-ledger/get?id=' + id })

export const getBoxunCommercialConcreteLedgerSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/commercial-concrete-ledger/simple-list', params })

export const listBoxunCommercialConcreteLedgerByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/commercial-concrete-ledger/list-by-condition', data })

export const createBoxunCommercialConcreteLedger = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/commercial-concrete-ledger/create', data })

export const upsertBoxunCommercialConcreteLedger = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/commercial-concrete-ledger/upsert', data })

export const updateBoxunCommercialConcreteLedger = (data: EntityInput) => request.put<number>({ url: '/boxun/commercial-concrete-ledger/update', data })

export const deleteBoxunCommercialConcreteLedger = (id: EntityId) => request.delete<boolean>({ url: '/boxun/commercial-concrete-ledger/delete?id=' + id })

export const deleteBoxunCommercialConcreteLedgerList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/commercial-concrete-ledger/delete-list', params: { ids: ids.join(',') } })

export interface SpecimenGroupNumbers {
  numberOfStandardCuringSpecimenGroups: number
  numberOfSetsOfImpermeableTestPieces: number
  numberOfSpecimensInTheSameCulture: number
  numberOfDemoldingSpecimenGroups: number
}

/** 试件组数计算（原 classNumber）。 */
export const calculateBoxunCommercialConcreteLedgerGroups = (params: {
  pouringPosition: string
  strengthGrade?: string
  impermeabilityLevel?: string
  volumeSum: number
}) => request.get<SpecimenGroupNumbers>({ url: '/boxun/commercial-concrete-ledger/specimen-group-numbers', params })

/** 由商混台账生成试块留置台账、旁站记录与混凝土施工记录。 */
export const generateBoxunCommercialConcreteLedgerRecords = (ids: EntityId[]) =>
  request.post<{ blockRetentionLedgerCount: number; bystanderRecordCount: number; concreteRecordCount: number }>({
    url: '/boxun/commercial-concrete-ledger/generate-various-records',
    data: { ids: ids.map((id) => String(id)) }
  })

/** 删除商混台账关联记录。 */
export const deleteBoxunCommercialConcreteLedgerRelatedRecords = (projectId: string) =>
  request.post<number>({ url: '/boxun/commercial-concrete-ledger/delete-various-records', data: { projectId } })

/** 按项目删除商混记录（原 deleteByProjectId）。 */
export const deleteBoxunCommercialConcreteLedgerByProject = (projectId: string) =>
  request.post<number>({ url: '/boxun/commercial-concrete-ledger/delete-by-project-id', params: { projectId } })

/** 批量新增（原 addBatch）。 */
export const addBatchBoxunCommercialConcreteLedger = (rows: EntityInput[]) =>
  request.post<number>({ url: '/boxun/commercial-concrete-ledger/add-batch', data: rows })
