<!-- generated by studio，请勿手工修改。 -->
<template>
  <ContentWrap>
    <el-form ref="queryFormRef" :inline="true" :model="queryParams" class="-mb-15px">
        <el-form-item label="楼号" prop="buildingNo">
          <el-input v-model="queryParams.buildingNo" clearable placeholder="请输入楼号" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="工程部位" prop="concatPosition">
          <el-input v-model="queryParams.concatPosition" clearable placeholder="请输入工程部位" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="商混站名称" prop="nameOfCommercialMixingStation">
          <el-input v-model="queryParams.nameOfCommercialMixingStation" clearable placeholder="请输入商混站名称" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="强度等级" prop="strengthGrade">
          <el-input v-model="queryParams.strengthGrade" clearable placeholder="请输入强度等级" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="强度备注" prop="strengthRemarks">
          <el-input v-model="queryParams.strengthRemarks" clearable placeholder="请输入强度备注" @keyup.enter="handleQuery" />
        </el-form-item>
      <el-form-item>
        <el-button @click="handleQuery"><Icon class="mr-5px" icon="ep:search" />查询</el-button>
        <el-button @click="resetQuery"><Icon class="mr-5px" icon="ep:refresh" />重置</el-button>
          <el-button type="primary" @click="openForm('create')">
            <Icon class="mr-5px" icon="ep:plus" />新增
          </el-button>
          <el-button :disabled="checkedIds.length === 0" type="primary" plain @click="handleGenerateRecords">
            <Icon class="mr-5px" icon="ep:magic-stick" />生成各类记录
          </el-button>
          <el-button type="warning" plain @click="handleDeleteRelatedRecords">
            <Icon class="mr-5px" icon="ep:delete" />删除关联记录
          </el-button>
          <el-button type="danger" plain @click="handleDeleteByProject">
            <Icon class="mr-5px" icon="ep:delete" />按项目删除
          </el-button>
          <el-button :loading="exportLoading" type="success" @click="handleExport">
            <Icon class="mr-5px" icon="ep:download" />导出
          </el-button>
          <el-button :disabled="checkedIds.length === 0" type="danger" @click="handleDeleteBatch">
            <Icon class="mr-5px" icon="ep:delete" />批量删除
          </el-button>
      </el-form-item>
    </el-form>
  </ContentWrap>

  <ContentWrap>
    <el-table v-loading="loading" :data="rows" @selection-change="handleSelectionChange">
        <el-table-column align="center" type="selection" width="55" />
      <el-table-column align="center" label="行号" width="90">
        <template #default="scope">{{ (queryParams.pageNo - 1) * queryParams.pageSize + scope.$index + 1 }}</template>
      </el-table-column>
        <el-table-column label="项目id" prop="fkProjectId" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" :formatter="dateFormatter" label="浇筑日期" prop="productionDate" width="180" />
        <el-table-column label="楼号" prop="buildingNo" min-width="120" show-overflow-tooltip />
        <el-table-column label="工程部位" prop="concatPosition" min-width="120" show-overflow-tooltip />
        <el-table-column label="商混站名称" prop="nameOfCommercialMixingStation" min-width="120" show-overflow-tooltip />
        <el-table-column label="强度等级" prop="strengthGrade" min-width="120" show-overflow-tooltip />
        <el-table-column label="抗渗等级" prop="impermeabilityLevel" min-width="120" show-overflow-tooltip />
        <el-table-column label="强度备注" prop="strengthRemarks" min-width="120" show-overflow-tooltip />
        <el-table-column label="浇筑方量" prop="sumVolume" min-width="120" show-overflow-tooltip />
        <el-table-column label="标养试件组数" prop="numberOfStandardCuringSpecimenGroups" min-width="120" show-overflow-tooltip />
        <el-table-column label="抗渗试件组数" prop="numberOfSetsOfImpermeableTestPieces" min-width="120" show-overflow-tooltip />
        <el-table-column label="同养试件组数" prop="numberOfSpecimensInTheSameCulture" min-width="120" show-overflow-tooltip />
        <el-table-column label="拆模试件组数" prop="numberOfDemoldingSpecimenGroups" min-width="120" show-overflow-tooltip />
        <el-table-column label="同养温度" prop="syntrophicTemperature" min-width="120" show-overflow-tooltip />
        <el-table-column label="随车资料" prop="accompanyingDocuments" min-width="120" show-overflow-tooltip />
        <el-table-column label="28天资料" prop="day28Data" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" fixed="right" label="操作" width="160">
          <template #default="scope">
            <el-button link type="primary" @click="openDetail(scope.row.id)">查看</el-button>
            <el-button link type="primary" @click="openForm('update', scope.row.id)">编辑</el-button>
            <el-button link type="danger" @click="handleDelete(scope.row.id)">删除</el-button>
          </template>
        </el-table-column>
    </el-table>
    <Pagination v-model:limit="queryParams.pageSize" v-model:page="queryParams.pageNo" :total="total" @pagination="getList" />
  </ContentWrap>

  <BoxunCommercialConcreteLedgerForm ref="formRef" @success="getList" />
  <BoxunCommercialConcreteLedgerDetail ref="detailRef" />
</template>

<script setup lang="ts">
import { dateFormatter } from '@/utils/formatTime'
import request from '@/config/axios'
import download from '@/utils/download'
import * as BoxunCommercialConcreteLedgerApi from './BoxunCommercialConcreteLedgerApi'
import BoxunCommercialConcreteLedgerForm from './BoxunCommercialConcreteLedgerForm.vue'
import BoxunCommercialConcreteLedgerDetail from './BoxunCommercialConcreteLedgerDetail.vue'
import { currentProjectId, loadProjects } from '@/features/project/projectContext'

type BoxunCommercialConcreteLedgerRow = Awaited<ReturnType<typeof BoxunCommercialConcreteLedgerApi.getBoxunCommercialConcreteLedgerPage>>['list'][number]
type EntityId = string | number

defineOptions({ name: 'BoxunCommercialConcreteLedger' })

const message = useMessage()
const { t } = useI18n()
const loading = ref(false)
const total = ref(0)
const rows = ref<BoxunCommercialConcreteLedgerRow[]>([])
const queryFormRef = ref()
const queryParams = reactive({
  pageNo: 1,
  pageSize: 10,
  buildingNo: '',
  concatPosition: '',
  nameOfCommercialMixingStation: '',
  strengthGrade: '',
  strengthRemarks: ''
})



const getList = async () => {
  loading.value = true
  try {
    await loadProjects()
    const data = await BoxunCommercialConcreteLedgerApi.getBoxunCommercialConcreteLedgerPage(queryParams)
    rows.value = data.list
    total.value = Number(data.total)
  } finally {
    loading.value = false
  }
}

const handleQuery = () => {
  queryParams.pageNo = 1
  getList()
}

const resetQuery = () => {

  queryFormRef.value?.resetFields()

  handleQuery()
}

const formRef = ref()
const openForm = (type: 'create' | 'update', id?: EntityId) => {
  formRef.value?.open(type, id, type === 'create' ? undefined : undefined)
}


const detailRef = ref()
const openDetail = (id: EntityId) => {
  detailRef.value?.open(id)
}



const handleDelete = async (id?: EntityId) => {
  if (id === undefined) return
  await message.delConfirm()
  await BoxunCommercialConcreteLedgerApi.deleteBoxunCommercialConcreteLedger(id)
  message.success(t('common.delSuccess'))
  await getList()
}

const checkedIds = ref<EntityId[]>([])
const handleSelectionChange = (rows: BoxunCommercialConcreteLedgerRow[]) => {
  checkedIds.value = rows.map((row) => row.id).filter((id): id is EntityId => id !== undefined)
}

const handleDeleteBatch = async () => {
  await message.delConfirm()
  await BoxunCommercialConcreteLedgerApi.deleteBoxunCommercialConcreteLedgerList(checkedIds.value)
  message.success(t('common.delSuccess'))
  checkedIds.value = []
  await getList()
}
const exportLoading = ref(false)
const handleExport = async () => {
  await message.exportConfirm()
  exportLoading.value = true
  try {
    const data = await request.download({ url: '/boxun/commercial-concrete-ledger/export-excel', params: queryParams })
    download.excel(data, 'boxunCommercialConcreteLedger.xls')
  } finally {
    exportLoading.value = false
  }
}

/** 由选中的商混台账生成试块留置台账、旁站记录与混凝土施工记录。 */
const handleGenerateRecords = async () => {
  if (checkedIds.value.length === 0) return
  const result = await BoxunCommercialConcreteLedgerApi.generateBoxunCommercialConcreteLedgerRecords(checkedIds.value)
  message.success(
    `已生成试块留置台账 ${result.blockRetentionLedgerCount} 条、旁站记录 ${result.bystanderRecordCount} 条、混凝土施工记录 ${result.concreteRecordCount} 条`
  )
  await getList()
}

/** 删除当前项目下的商混关联记录。 */
const handleDeleteRelatedRecords = async () => {
  if (!currentProjectId.value) {
    message.warning('请先选择项目')
    return
  }
  await message.delConfirm()
  const removed = await BoxunCommercialConcreteLedgerApi.deleteBoxunCommercialConcreteLedgerRelatedRecords(currentProjectId.value)
  message.success(`已删除 ${removed} 组关联记录`)
}

/** 按当前项目删除商混台账。 */
const handleDeleteByProject = async () => {
  if (!currentProjectId.value) {
    message.warning('请先选择项目')
    return
  }
  await message.delConfirm()
  const removed = await BoxunCommercialConcreteLedgerApi.deleteBoxunCommercialConcreteLedgerByProject(currentProjectId.value)
  message.success(`已删除 ${removed} 条商混记录`)
  await getList()
}

onMounted(getList)
</script>
