<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看委托单常用样品配置" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="上级id">
        {{ detail?.pid ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="表头">
        {{ detail?.header ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="材料名称">
        {{ detail?.materialName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="检验依据">
        {{ detail?.inspectionBasis ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="规范编码">
        {{ detail?.normativeEncoding ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="排序">
        {{ detail?.sortNo ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="备注1">
        {{ detail?.note1 ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="备注2">
        {{ detail?.note2 ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="备注3">
        {{ detail?.note3 ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="备注4">
        {{ detail?.note4 ?? '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import * as BoxunDelegationOrderContextApi from './BoxunDelegationOrderContextApi'

type BoxunDelegationOrderContextDetail = Awaited<ReturnType<typeof BoxunDelegationOrderContextApi.getBoxunDelegationOrderContext>>
type EntityId = string | number

defineOptions({ name: 'BoxunDelegationOrderContextDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunDelegationOrderContextDetail>()

const open = async (id: EntityId) => {
  detail.value = undefined
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunDelegationOrderContextApi.getBoxunDelegationOrderContext(id)
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
