// generated by studio，请勿手工修改。
import request from '@/config/axios'

export type EntityId = string | number
export type EntityInput = Record<string, any>
export type EntityRecord = EntityInput & { id: EntityId }

export interface PageResult<T> {
  list: T[]
  total: number
}

export const getBoxunExperimentalReportPage = (params: Record<string, unknown>) => request.get<PageResult<EntityRecord>>({ url: '/boxun/experimental-report/page', params })

export const getBoxunExperimentalReport = (id: EntityId) => request.get<EntityRecord>({ url: '/boxun/experimental-report/get?id=' + id })

export const getBoxunExperimentalReportSimpleList = (params?: Record<string, unknown>) => request.get<EntityRecord[]>({ url: '/boxun/experimental-report/simple-list', params })

export const listBoxunExperimentalReportByCondition = (data?: EntityInput) => request.post<EntityRecord[]>({ url: '/boxun/experimental-report/list-by-condition', data })

export const createBoxunExperimentalReport = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/experimental-report/create', data })

export const upsertBoxunExperimentalReport = (data: EntityInput) => request.post<EntityRecord>({ url: '/boxun/experimental-report/upsert', data })

export const updateBoxunExperimentalReport = (data: EntityInput) => request.put<number>({ url: '/boxun/experimental-report/update', data })

export const deleteBoxunExperimentalReport = (id: EntityId) => request.delete<boolean>({ url: '/boxun/experimental-report/delete?id=' + id })

export const deleteBoxunExperimentalReportList = (ids: EntityId[]) => request.delete<boolean>({ url: '/boxun/experimental-report/delete-list', params: { ids: ids.join(',') } })
