<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog
    v-model="dialogVisible"
    :close-on-click-modal="false"
    :title="dialogTitle"
    max-height="60vh"
    scroll
    width="min(760px, calc(100vw - 32px))"
  >
    <el-form ref="formRef" v-loading="formLoading" :model="formData" :rules="formRules" label-position="top">
<el-row class="!mx-0" :gutter="16">
        <el-col :span="12">
          <el-form-item label="项目id" prop="projectId">
            <el-input v-model="formData.projectId" placeholder="请输入项目id" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="单位名称" prop="unitName">
            <el-input v-model="formData.unitName" placeholder="请输入单位名称" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="单位类型" prop="unitType">
            <el-input-number v-model="formData.unitType" class="!w-100%" controls-position="right" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="统一社会信用代码" prop="socialCreditCode">
            <el-input v-model="formData.socialCreditCode" placeholder="请输入统一社会信用代码" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="地址" prop="address">
            <el-input v-model="formData.address" placeholder="请输入地址" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="负责人姓名" prop="contactPerson">
            <el-input v-model="formData.contactPerson" placeholder="请输入负责人姓名" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="负责人电话" prop="phone">
            <el-input v-model="formData.phone" placeholder="请输入负责人电话" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="负责人身份证号" prop="idCard">
            <el-input v-model="formData.idCard" placeholder="请输入负责人身份证号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="法人姓名" prop="legalPersonName">
            <el-input v-model="formData.legalPersonName" placeholder="请输入法人姓名" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="法人电话" prop="legalPersonPhone">
            <el-input v-model="formData.legalPersonPhone" placeholder="请输入法人电话" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="法人身份证号" prop="legalPersonCard">
            <el-input v-model="formData.legalPersonCard" placeholder="请输入法人身份证号" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="单位logo" prop="companyLogo">
            <UploadImg v-model="formData.companyLogo" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="是否启用" prop="enableOrNot">
            <el-switch v-model="formData.enableOrNot" />
          </el-form-item>
        </el-col>
</el-row>
    </el-form>

    <template #footer>
      <el-button :disabled="formLoading" type="primary" @click="submitForm">确定</el-button>
      <el-button @click="dialogVisible = false">取消</el-button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import { UploadImg } from '@/components/UploadFile'
import * as BoxunProjectCompanyApi from './BoxunProjectCompanyApi'
import { currentProjectId, loadProjects } from '@/features/project/projectContext'

type BoxunProjectCompanyFormData = Parameters<typeof BoxunProjectCompanyApi.createBoxunProjectCompany>[0]
type EntityId = string | number


defineOptions({ name: 'BoxunProjectCompanyForm' })

const emit = defineEmits<{ success: [] }>()
const message = useMessage()
const { t } = useI18n()
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formLoading = ref(false)
const formType = ref<'create' | 'update'>('create')
const editingId = ref<EntityId>()
const formRef = ref()
const initialFormData = () => ({
  projectId: '',
  unitName: '',
  unitType: undefined,
  socialCreditCode: '',
  address: '',
  contactPerson: '',
  phone: '',
  idCard: '',
  legalPersonName: '',
  legalPersonPhone: '',
  legalPersonCard: '',
  companyLogo: '',
  enableOrNot: undefined
}) as BoxunProjectCompanyFormData
const formData = ref(initialFormData())
const formRules = reactive({

})






const open = async (type: 'create' | 'update', id?: EntityId, defaults?: Partial<BoxunProjectCompanyFormData>) => {

  formType.value = type
  editingId.value = id

  dialogTitle.value = type === 'create' ? '新增参建单位' : '修改参建单位'
  formData.value = { ...initialFormData(), ...defaults }
  formLoading.value = true
  dialogVisible.value = true
  try {
    if (type === 'create' && !formData.value.projectId) {
      await loadProjects()
      formData.value.projectId = currentProjectId.value
    }


    if (id !== undefined) {
      formData.value = { ...initialFormData(), ...await BoxunProjectCompanyApi.getBoxunProjectCompany(id) }

    }


  } finally {
    formLoading.value = false
    await nextTick()
    formRef.value?.clearValidate()

  }
}
defineExpose({ open })


const submitForm = async () => {
  if (formLoading.value) return



  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) {

    return
  }
  const inputFields = formType.value === 'create' ? ['projectId', 'unitName', 'unitType', 'socialCreditCode', 'address', 'contactPerson', 'phone', 'idCard', 'legalPersonName', 'legalPersonPhone', 'legalPersonCard', 'companyLogo', 'enableOrNot'] : ['id', 'projectId', 'unitName', 'unitType', 'socialCreditCode', 'address', 'contactPerson', 'phone', 'idCard', 'legalPersonName', 'legalPersonPhone', 'legalPersonCard', 'companyLogo', 'enableOrNot']
  const input = Object.fromEntries(inputFields.map((key) => [key, formData.value[key]]))

  formLoading.value = true
  try {
    if (formType.value === 'create') {
      await BoxunProjectCompanyApi.createBoxunProjectCompany(input)
      message.success(t('common.createSuccess'))
    } else {
      await BoxunProjectCompanyApi.updateBoxunProjectCompany(input)
      message.success(t('common.updateSuccess'))
    }
    dialogVisible.value = false
    emit('success')
  } finally {
    formLoading.value = false
  }
}
</script>
