<!-- generated by studio，请勿手工修改。 -->
<template>
  <Dialog v-model="dialogVisible" title="查看参建单位" width="760">
    <el-descriptions v-loading="loading" :column="2" border>
      <el-descriptions-item label="单位名称">
        {{ detail?.unitName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="单位类型">
        {{ detail?.unitType ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="统一社会信用代码">
        {{ detail?.socialCreditCode ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="地址">
        {{ detail?.address ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="负责人姓名">
        {{ detail?.contactPerson ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="负责人电话">
        {{ detail?.phone ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="负责人身份证号">
        {{ detail?.idCard ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="法人姓名">
        {{ detail?.legalPersonName ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="法人电话">
        {{ detail?.legalPersonPhone ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="法人身份证号">
        {{ detail?.legalPersonCard ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="单位logo">
        {{ detail?.companyLogo ?? '-' }}
      </el-descriptions-item>
      <el-descriptions-item label="是否启用">
        {{ detail?.enableOrNot ?? '-' }}
      </el-descriptions-item>
    </el-descriptions>
  </Dialog>
</template>

<script setup lang="ts">
import * as BoxunProjectCompanyApi from './BoxunProjectCompanyApi'

type BoxunProjectCompanyDetail = Awaited<ReturnType<typeof BoxunProjectCompanyApi.getBoxunProjectCompany>>
type EntityId = string | number

defineOptions({ name: 'BoxunProjectCompanyDetail' })

const dialogVisible = ref(false)
const loading = ref(false)
const detail = ref<BoxunProjectCompanyDetail>()

const open = async (id: EntityId) => {
  detail.value = undefined
  dialogVisible.value = true
  loading.value = true
  try {
    detail.value = await BoxunProjectCompanyApi.getBoxunProjectCompany(id)
  } finally {
    loading.value = false
  }
}
defineExpose({ open })
</script>
