<!-- generated by studio，请勿手工修改。 -->
<template>
  <ContentWrap>
    <el-form ref="queryFormRef" :inline="true" :model="queryParams" class="-mb-15px">
        <el-form-item label="单位名称" prop="unitName">
          <el-input v-model="queryParams.unitName" clearable placeholder="请输入单位名称" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="地址" prop="address">
          <el-input v-model="queryParams.address" clearable placeholder="请输入地址" @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="法人姓名" prop="legalPersonName">
          <el-input v-model="queryParams.legalPersonName" clearable placeholder="请输入法人姓名" @keyup.enter="handleQuery" />
        </el-form-item>
      <el-form-item>
        <el-button @click="handleQuery"><Icon class="mr-5px" icon="ep:search" />查询</el-button>
        <el-button @click="resetQuery"><Icon class="mr-5px" icon="ep:refresh" />重置</el-button>
          <el-button type="primary" @click="openForm('create')">
            <Icon class="mr-5px" icon="ep:plus" />新增
          </el-button>
          <el-button :loading="exportLoading" type="success" @click="handleExport">
            <Icon class="mr-5px" icon="ep:download" />导出
          </el-button>
          <el-button :disabled="checkedIds.length === 0" type="danger" @click="handleDeleteBatch">
            <Icon class="mr-5px" icon="ep:delete" />批量删除
          </el-button>
      </el-form-item>
    </el-form>
  </ContentWrap>

  <ContentWrap>
    <el-table v-loading="loading" :data="rows" @selection-change="handleSelectionChange">
        <el-table-column align="center" type="selection" width="55" />
      <el-table-column align="center" label="行号" width="90">
        <template #default="scope">{{ (queryParams.pageNo - 1) * queryParams.pageSize + scope.$index + 1 }}</template>
      </el-table-column>
        <el-table-column label="单位名称" prop="unitName" min-width="120" show-overflow-tooltip />
        <el-table-column label="单位类型" prop="unitType" min-width="120" show-overflow-tooltip />
        <el-table-column label="统一社会信用代码" prop="socialCreditCode" min-width="120" show-overflow-tooltip />
        <el-table-column label="地址" prop="address" min-width="120" show-overflow-tooltip />
        <el-table-column label="负责人姓名" prop="contactPerson" min-width="120" show-overflow-tooltip />
        <el-table-column label="负责人电话" prop="phone" min-width="120" show-overflow-tooltip />
        <el-table-column label="负责人身份证号" prop="idCard" min-width="120" show-overflow-tooltip />
        <el-table-column label="法人姓名" prop="legalPersonName" min-width="120" show-overflow-tooltip />
        <el-table-column label="法人电话" prop="legalPersonPhone" min-width="120" show-overflow-tooltip />
        <el-table-column label="法人身份证号" prop="legalPersonCard" min-width="120" show-overflow-tooltip />
        <el-table-column label="单位logo" prop="companyLogo" min-width="120" show-overflow-tooltip />
        <el-table-column label="是否启用" prop="enableOrNot" min-width="120" show-overflow-tooltip />
        <el-table-column align="center" fixed="right" label="操作" width="160">
          <template #default="scope">
            <el-button link type="primary" @click="openDetail(scope.row.id)">查看</el-button>
            <el-button link type="primary" @click="openForm('update', scope.row.id)">编辑</el-button>
            <el-button link type="danger" @click="handleDelete(scope.row.id)">删除</el-button>
          </template>
        </el-table-column>
    </el-table>
    <Pagination v-model:limit="queryParams.pageSize" v-model:page="queryParams.pageNo" :total="total" @pagination="getList" />
  </ContentWrap>

  <BoxunProjectCompanyForm ref="formRef" @success="getList" />
  <BoxunProjectCompanyDetail ref="detailRef" />
</template>

<script setup lang="ts">
import { onBeforeUnmount } from 'vue'
import request from '@/config/axios'
import download from '@/utils/download'
import * as BoxunProjectCompanyApi from './BoxunProjectCompanyApi'
import BoxunProjectCompanyForm from './BoxunProjectCompanyForm.vue'
import BoxunProjectCompanyDetail from './BoxunProjectCompanyDetail.vue'
import { currentProjectId, loadProjects } from '@/features/project/projectContext'

type BoxunProjectCompanyRow = Awaited<ReturnType<typeof BoxunProjectCompanyApi.getBoxunProjectCompanyPage>>['list'][number]
type EntityId = string | number

defineOptions({ name: 'BoxunProjectCompany' })

const message = useMessage()
const { t } = useI18n()
const loading = ref(false)
const total = ref(0)
const rows = ref<BoxunProjectCompanyRow[]>([])
const queryFormRef = ref()
const queryParams = reactive({
  pageNo: 1,
  pageSize: 10,
  projectId: '',
  unitName: '',
  address: '',
  legalPersonName: ''
})



const getList = async () => {
  loading.value = true
  try {
    await loadProjects()
    queryParams.projectId = currentProjectId.value
    const data = await BoxunProjectCompanyApi.getBoxunProjectCompanyPage(queryParams)
    rows.value = data.list
    total.value = Number(data.total)
  } finally {
    loading.value = false
  }
}

const handleQuery = () => {
  queryParams.pageNo = 1
  getList()
}

const resetQuery = () => {

  queryFormRef.value?.resetFields()

  handleQuery()
}

const formRef = ref()
const openForm = (type: 'create' | 'update', id?: EntityId) => {
  formRef.value?.open(type, id, type === 'create' ? undefined : undefined)
}


const detailRef = ref()
const openDetail = (id: EntityId) => {
  detailRef.value?.open(id)
}



const handleDelete = async (id?: EntityId) => {
  if (id === undefined) return
  await message.delConfirm()
  await BoxunProjectCompanyApi.deleteBoxunProjectCompany(id)
  message.success(t('common.delSuccess'))
  await getList()
}

const checkedIds = ref<EntityId[]>([])
const handleSelectionChange = (rows: BoxunProjectCompanyRow[]) => {
  checkedIds.value = rows.map((row) => row.id).filter((id): id is EntityId => id !== undefined)
}

const handleDeleteBatch = async () => {
  await message.delConfirm()
  await BoxunProjectCompanyApi.deleteBoxunProjectCompanyList(checkedIds.value)
  message.success(t('common.delSuccess'))
  checkedIds.value = []
  await getList()
}
const exportLoading = ref(false)
const handleExport = async () => {
  await message.exportConfirm()
  exportLoading.value = true
  try {
    const data = await request.download({ url: '/boxun/project-company/export-excel', params: queryParams })
    download.excel(data, 'boxunProjectCompany.xls')
  } finally {
    exportLoading.value = false
  }
}

onMounted(getList)

const handleProjectChanged = () => {
  queryParams.pageNo = 1
  void getList()
}

onMounted(() => {
  window.addEventListener('boxun:project-changed', handleProjectChanged)
})

onBeforeUnmount(() => {
  window.removeEventListener('boxun:project-changed', handleProjectChanged)
})
</script>
